package seed

import "shiny-collection/internal/model"

// AllPokemon contains all 1025 Pokémon with national numbers,
// English names, Chinese names, and types.
var AllPokemon = []model.Pokemon{
	{NationalNo: 1, Name: "Bulbasaur", NameCN: "妙蛙种子", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 2, Name: "Ivysaur", NameCN: "妙蛙草", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 3, Name: "Venusaur", NameCN: "妙蛙花", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 4, Name: "Charmander", NameCN: "小火龙", Type1: "Fire", },
	{NationalNo: 5, Name: "Charmeleon", NameCN: "火恐龙", Type1: "Fire", },
	{NationalNo: 6, Name: "Charizard", NameCN: "喷火龙", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 7, Name: "Squirtle", NameCN: "杰尼龟", Type1: "Water", },
	{NationalNo: 8, Name: "Wartortle", NameCN: "卡咪龟", Type1: "Water", },
	{NationalNo: 9, Name: "Blastoise", NameCN: "水箭龟", Type1: "Water", },
	{NationalNo: 10, Name: "Caterpie", NameCN: "绿毛虫", Type1: "Bug", },
	{NationalNo: 11, Name: "Metapod", NameCN: "铁甲蛹", Type1: "Bug", },
	{NationalNo: 12, Name: "Butterfree", NameCN: "巴大蝶", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 13, Name: "Weedle", NameCN: "独角虫", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 14, Name: "Kakuna", NameCN: "铁壳蛹", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 15, Name: "Beedrill", NameCN: "大针蜂", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 16, Name: "Pidgey", NameCN: "波波", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 17, Name: "Pidgeotto", NameCN: "比比鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 18, Name: "Pidgeot", NameCN: "大比鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 19, Name: "Rattata", NameCN: "小拉达", Type1: "Normal", },
	{NationalNo: 20, Name: "Raticate", NameCN: "拉达", Type1: "Normal", },
	{NationalNo: 21, Name: "Spearow", NameCN: "烈雀", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 22, Name: "Fearow", NameCN: "大嘴雀", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 23, Name: "Ekans", NameCN: "阿柏蛇", Type1: "Poison", },
	{NationalNo: 24, Name: "Arbok", NameCN: "阿柏怪", Type1: "Poison", },
	{NationalNo: 25, Name: "Pikachu", NameCN: "皮卡丘", Type1: "Electric", },
	{NationalNo: 26, Name: "Raichu", NameCN: "雷丘", Type1: "Electric", },
	{NationalNo: 27, Name: "Sandshrew", NameCN: "穿山鼠", Type1: "Ground", },
	{NationalNo: 28, Name: "Sandslash", NameCN: "穿山王", Type1: "Ground", },
	{NationalNo: 29, Name: "Nidoran♀", NameCN: "尼多兰", Type1: "Poison", },
	{NationalNo: 30, Name: "Nidorina", NameCN: "尼多娜", Type1: "Poison", },
	{NationalNo: 31, Name: "Nidoqueen", NameCN: "尼多后", Type1: "Poison", Type2: "Ground",},
	{NationalNo: 32, Name: "Nidoran♂", NameCN: "尼多朗", Type1: "Poison", },
	{NationalNo: 33, Name: "Nidorino", NameCN: "尼多力诺", Type1: "Poison", },
	{NationalNo: 34, Name: "Nidoking", NameCN: "尼多王", Type1: "Poison", Type2: "Ground",},
	{NationalNo: 35, Name: "Clefairy", NameCN: "皮皮", Type1: "Fairy", },
	{NationalNo: 36, Name: "Clefable", NameCN: "皮可西", Type1: "Fairy", },
	{NationalNo: 37, Name: "Vulpix", NameCN: "六尾", Type1: "Fire", },
	{NationalNo: 38, Name: "Ninetales", NameCN: "九尾", Type1: "Fire", },
	{NationalNo: 39, Name: "Jigglypuff", NameCN: "胖丁", Type1: "Normal", Type2: "Fairy",},
	{NationalNo: 40, Name: "Wigglytuff", NameCN: "胖可丁", Type1: "Normal", Type2: "Fairy",},
	{NationalNo: 41, Name: "Zubat", NameCN: "超音蝠", Type1: "Poison", Type2: "Flying",},
	{NationalNo: 42, Name: "Golbat", NameCN: "大嘴蝠", Type1: "Poison", Type2: "Flying",},
	{NationalNo: 43, Name: "Oddish", NameCN: "走路草", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 44, Name: "Gloom", NameCN: "臭臭花", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 45, Name: "Vileplume", NameCN: "霸王花", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 46, Name: "Paras", NameCN: "派拉斯", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 47, Name: "Parasect", NameCN: "派拉斯特", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 48, Name: "Venonat", NameCN: "毛球", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 49, Name: "Venomoth", NameCN: "摩鲁蛾", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 50, Name: "Diglett", NameCN: "地鼠", Type1: "Ground", },
	{NationalNo: 51, Name: "Dugtrio", NameCN: "三地鼠", Type1: "Ground", },
	{NationalNo: 52, Name: "Meowth", NameCN: "喵喵", Type1: "Normal", },
	{NationalNo: 53, Name: "Persian", NameCN: "猫老大", Type1: "Normal", },
	{NationalNo: 54, Name: "Psyduck", NameCN: "可达鸭", Type1: "Water", },
	{NationalNo: 55, Name: "Golduck", NameCN: "哥达鸭", Type1: "Water", },
	{NationalNo: 56, Name: "Mankey", NameCN: "猴怪", Type1: "Fighting", },
	{NationalNo: 57, Name: "Primeape", NameCN: "火暴猴", Type1: "Fighting", },
	{NationalNo: 58, Name: "Growlithe", NameCN: "卡蒂狗", Type1: "Fire", },
	{NationalNo: 59, Name: "Arcanine", NameCN: "风速狗", Type1: "Fire", },
	{NationalNo: 60, Name: "Poliwag", NameCN: "蚊香蝌蚪", Type1: "Water", },
	{NationalNo: 61, Name: "Poliwhirl", NameCN: "蚊香君", Type1: "Water", },
	{NationalNo: 62, Name: "Poliwrath", NameCN: "蚊香泳士", Type1: "Water", Type2: "Fighting",},
	{NationalNo: 63, Name: "Abra", NameCN: "凯西", Type1: "Psychic", },
	{NationalNo: 64, Name: "Kadabra", NameCN: "勇基拉", Type1: "Psychic", },
	{NationalNo: 65, Name: "Alakazam", NameCN: "胡地", Type1: "Psychic", },
	{NationalNo: 66, Name: "Machop", NameCN: "腕力", Type1: "Fighting", },
	{NationalNo: 67, Name: "Machoke", NameCN: "豪力", Type1: "Fighting", },
	{NationalNo: 68, Name: "Machamp", NameCN: "怪力", Type1: "Fighting", },
	{NationalNo: 69, Name: "Bellsprout", NameCN: "喇叭芽", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 70, Name: "Weepinbell", NameCN: "口呆花", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 71, Name: "Victreebel", NameCN: "大食花", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 72, Name: "Tentacool", NameCN: "玛瑙水母", Type1: "Water", Type2: "Poison",},
	{NationalNo: 73, Name: "Tentacruel", NameCN: "毒刺水母", Type1: "Water", Type2: "Poison",},
	{NationalNo: 74, Name: "Geodude", NameCN: "小拳石", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 75, Name: "Graveler", NameCN: "隆隆石", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 76, Name: "Golem", NameCN: "隆隆岩", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 77, Name: "Ponyta", NameCN: "小火马", Type1: "Fire", },
	{NationalNo: 78, Name: "Rapidash", NameCN: "烈焰马", Type1: "Fire", },
	{NationalNo: 79, Name: "Slowpoke", NameCN: "呆呆兽", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 80, Name: "Slowbro", NameCN: "呆壳兽", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 81, Name: "Magnemite", NameCN: "小磁怪", Type1: "Electric", Type2: "Steel",},
	{NationalNo: 82, Name: "Magneton", NameCN: "三合一磁怪", Type1: "Electric", Type2: "Steel",},
	{NationalNo: 83, Name: "Farfetch'd", NameCN: "大葱鸭", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 84, Name: "Doduo", NameCN: "嘟嘟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 85, Name: "Dodrio", NameCN: "嘟嘟利", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 86, Name: "Seel", NameCN: "小海狮", Type1: "Water", },
	{NationalNo: 87, Name: "Dewgong", NameCN: "白海狮", Type1: "Water", Type2: "Ice",},
	{NationalNo: 88, Name: "Grimer", NameCN: "臭泥", Type1: "Poison", },
	{NationalNo: 89, Name: "Muk", NameCN: "臭臭泥", Type1: "Poison", },
	{NationalNo: 90, Name: "Shellder", NameCN: "大舌贝", Type1: "Water", },
	{NationalNo: 91, Name: "Cloyster", NameCN: "刺甲贝", Type1: "Water", Type2: "Ice",},
	{NationalNo: 92, Name: "Gastly", NameCN: "鬼斯", Type1: "Ghost", Type2: "Poison",},
	{NationalNo: 93, Name: "Haunter", NameCN: "鬼斯通", Type1: "Ghost", Type2: "Poison",},
	{NationalNo: 94, Name: "Gengar", NameCN: "耿鬼", Type1: "Ghost", Type2: "Poison",},
	{NationalNo: 95, Name: "Onix", NameCN: "大岩蛇", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 96, Name: "Drowzee", NameCN: "催眠貘", Type1: "Psychic", },
	{NationalNo: 97, Name: "Hypno", NameCN: "引梦貘人", Type1: "Psychic", },
	{NationalNo: 98, Name: "Krabby", NameCN: "大钳蟹", Type1: "Water", },
	{NationalNo: 99, Name: "Kingler", NameCN: "巨钳蟹", Type1: "Water", },
	{NationalNo: 100, Name: "Voltorb", NameCN: "霹雳电球", Type1: "Electric", },
	{NationalNo: 101, Name: "Electrode", NameCN: "顽皮雷弹", Type1: "Electric", },
	{NationalNo: 102, Name: "Exeggcute", NameCN: "蛋蛋", Type1: "Grass", Type2: "Psychic",},
	{NationalNo: 103, Name: "Exeggutor", NameCN: "椰蛋树", Type1: "Grass", Type2: "Psychic",},
	{NationalNo: 104, Name: "Cubone", NameCN: "卡拉卡拉", Type1: "Ground", },
	{NationalNo: 105, Name: "Marowak", NameCN: "嘎啦嘎啦", Type1: "Ground", },
	{NationalNo: 106, Name: "Hitmonlee", NameCN: "飞腿郎", Type1: "Fighting", },
	{NationalNo: 107, Name: "Hitmonchan", NameCN: "快拳郎", Type1: "Fighting", },
	{NationalNo: 108, Name: "Lickitung", NameCN: "大舌头", Type1: "Normal", },
	{NationalNo: 109, Name: "Koffing", NameCN: "瓦斯弹", Type1: "Poison", },
	{NationalNo: 110, Name: "Weezing", NameCN: "双弹瓦斯", Type1: "Poison", },
	{NationalNo: 111, Name: "Rhyhorn", NameCN: "独角犀牛", Type1: "Ground", Type2: "Rock",},
	{NationalNo: 112, Name: "Rhydon", NameCN: "钻角犀兽", Type1: "Ground", Type2: "Rock",},
	{NationalNo: 113, Name: "Chansey", NameCN: "吉利蛋", Type1: "Normal", },
	{NationalNo: 114, Name: "Tangela", NameCN: "蔓藤怪", Type1: "Grass", },
	{NationalNo: 115, Name: "Kangaskhan", NameCN: "袋兽", Type1: "Normal", },
	{NationalNo: 116, Name: "Horsea", NameCN: "墨海马", Type1: "Water", },
	{NationalNo: 117, Name: "Seadra", NameCN: "海刺龙", Type1: "Water", },
	{NationalNo: 118, Name: "Goldeen", NameCN: "角金鱼", Type1: "Water", },
	{NationalNo: 119, Name: "Seaking", NameCN: "金鱼王", Type1: "Water", },
	{NationalNo: 120, Name: "Staryu", NameCN: "海星星", Type1: "Water", },
	{NationalNo: 121, Name: "Starmie", NameCN: "宝石海星", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 122, Name: "Mr. Mime", NameCN: "魔墙人偶", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 123, Name: "Scyther", NameCN: "飞天螳螂", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 124, Name: "Jynx", NameCN: "迷唇姐", Type1: "Ice", Type2: "Psychic",},
	{NationalNo: 125, Name: "Electabuzz", NameCN: "电击兽", Type1: "Electric", },
	{NationalNo: 126, Name: "Magmar", NameCN: "鸭嘴火兽", Type1: "Fire", },
	{NationalNo: 127, Name: "Pinsir", NameCN: "凯罗斯", Type1: "Bug", },
	{NationalNo: 128, Name: "Tauros", NameCN: "肯泰罗", Type1: "Normal", },
	{NationalNo: 129, Name: "Magikarp", NameCN: "鲤鱼王", Type1: "Water", },
	{NationalNo: 130, Name: "Gyarados", NameCN: "暴鲤龙", Type1: "Water", Type2: "Flying",},
	{NationalNo: 131, Name: "Lapras", NameCN: "拉普拉斯", Type1: "Water", Type2: "Ice",},
	{NationalNo: 132, Name: "Ditto", NameCN: "百变怪", Type1: "Normal", },
	{NationalNo: 133, Name: "Eevee", NameCN: "伊布", Type1: "Normal", },
	{NationalNo: 134, Name: "Vaporeon", NameCN: "水伊布", Type1: "Water", },
	{NationalNo: 135, Name: "Jolteon", NameCN: "雷伊布", Type1: "Electric", },
	{NationalNo: 136, Name: "Flareon", NameCN: "火伊布", Type1: "Fire", },
	{NationalNo: 137, Name: "Porygon", NameCN: "多边兽", Type1: "Normal", },
	{NationalNo: 138, Name: "Omanyte", NameCN: "菊石兽", Type1: "Rock", Type2: "Water",},
	{NationalNo: 139, Name: "Omastar", NameCN: "多刺菊石兽", Type1: "Rock", Type2: "Water",},
	{NationalNo: 140, Name: "Kabuto", NameCN: "化石盔", Type1: "Rock", Type2: "Water",},
	{NationalNo: 141, Name: "Kabutops", NameCN: "镰刀盔", Type1: "Rock", Type2: "Water",},
	{NationalNo: 142, Name: "Aerodactyl", NameCN: "化石翼龙", Type1: "Rock", Type2: "Flying",},
	{NationalNo: 143, Name: "Snorlax", NameCN: "卡比兽", Type1: "Normal", },
	{NationalNo: 144, Name: "Articuno", NameCN: "急冻鸟", Type1: "Ice", Type2: "Flying",},
	{NationalNo: 145, Name: "Zapdos", NameCN: "闪电鸟", Type1: "Electric", Type2: "Flying",},
	{NationalNo: 146, Name: "Moltres", NameCN: "火焰鸟", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 147, Name: "Dratini", NameCN: "迷你龙", Type1: "Dragon", },
	{NationalNo: 148, Name: "Dragonair", NameCN: "哈克龙", Type1: "Dragon", },
	{NationalNo: 149, Name: "Dragonite", NameCN: "快龙", Type1: "Dragon", Type2: "Flying",},
	{NationalNo: 150, Name: "Mewtwo", NameCN: "超梦", Type1: "Psychic", },
	{NationalNo: 151, Name: "Mew", NameCN: "梦幻", Type1: "Psychic", },
	{NationalNo: 152, Name: "Chikorita", NameCN: "菊草叶", Type1: "Grass", },
	{NationalNo: 153, Name: "Bayleef", NameCN: "月桂叶", Type1: "Grass", },
	{NationalNo: 154, Name: "Meganium", NameCN: "大竺葵", Type1: "Grass", },
	{NationalNo: 155, Name: "Cyndaquil", NameCN: "火球鼠", Type1: "Fire", },
	{NationalNo: 156, Name: "Quilava", NameCN: "火岩鼠", Type1: "Fire", },
	{NationalNo: 157, Name: "Typhlosion", NameCN: "火暴兽", Type1: "Fire", },
	{NationalNo: 158, Name: "Totodile", NameCN: "小锯鳄", Type1: "Water", },
	{NationalNo: 159, Name: "Croconaw", NameCN: "蓝鳄", Type1: "Water", },
	{NationalNo: 160, Name: "Feraligatr", NameCN: "大力鳄", Type1: "Water", },
	{NationalNo: 161, Name: "Sentret", NameCN: "尾立", Type1: "Normal", },
	{NationalNo: 162, Name: "Furret", NameCN: "大尾立", Type1: "Normal", },
	{NationalNo: 163, Name: "Hoothoot", NameCN: "咕咕", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 164, Name: "Noctowl", NameCN: "猫头夜鹰", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 165, Name: "Ledyba", NameCN: "芭瓢虫", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 166, Name: "Ledian", NameCN: "安瓢虫", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 167, Name: "Spinarak", NameCN: "圆丝蛛", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 168, Name: "Ariados", NameCN: "阿利多斯", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 169, Name: "Crobat", NameCN: "叉字蝠", Type1: "Poison", Type2: "Flying",},
	{NationalNo: 170, Name: "Chinchou", NameCN: "灯笼鱼", Type1: "Water", Type2: "Electric",},
	{NationalNo: 171, Name: "Lanturn", NameCN: "电灯怪", Type1: "Water", Type2: "Electric",},
	{NationalNo: 172, Name: "Pichu", NameCN: "皮丘", Type1: "Electric", },
	{NationalNo: 173, Name: "Cleffa", NameCN: "皮宝宝", Type1: "Fairy", },
	{NationalNo: 174, Name: "Igglybuff", NameCN: "宝宝丁", Type1: "Normal", Type2: "Fairy",},
	{NationalNo: 175, Name: "Togepi", NameCN: "波克比", Type1: "Fairy", },
	{NationalNo: 176, Name: "Togetic", NameCN: "波克基古", Type1: "Fairy", Type2: "Flying",},
	{NationalNo: 177, Name: "Natu", NameCN: "天然雀", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 178, Name: "Xatu", NameCN: "天然鸟", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 179, Name: "Mareep", NameCN: "咩利羊", Type1: "Electric", },
	{NationalNo: 180, Name: "Flaaffy", NameCN: "茸茸羊", Type1: "Electric", },
	{NationalNo: 181, Name: "Ampharos", NameCN: "电龙", Type1: "Electric", },
	{NationalNo: 182, Name: "Bellossom", NameCN: "美丽花", Type1: "Grass", },
	{NationalNo: 183, Name: "Marill", NameCN: "玛力露", Type1: "Water", Type2: "Fairy",},
	{NationalNo: 184, Name: "Azumarill", NameCN: "玛力露丽", Type1: "Water", Type2: "Fairy",},
	{NationalNo: 185, Name: "Sudowoodo", NameCN: "树才怪", Type1: "Rock", },
	{NationalNo: 186, Name: "Politoed", NameCN: "蚊香蛙皇", Type1: "Water", },
	{NationalNo: 187, Name: "Hoppip", NameCN: "毽子草", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 188, Name: "Skiploom", NameCN: "毽子花", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 189, Name: "Jumpluff", NameCN: "毽子棉", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 190, Name: "Aipom", NameCN: "长尾怪手", Type1: "Normal", },
	{NationalNo: 191, Name: "Sunkern", NameCN: "向日种子", Type1: "Grass", },
	{NationalNo: 192, Name: "Sunflora", NameCN: "向日花怪", Type1: "Grass", },
	{NationalNo: 193, Name: "Yanma", NameCN: "蜻蜻蜓", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 194, Name: "Wooper", NameCN: "乌波", Type1: "Water", Type2: "Ground",},
	{NationalNo: 195, Name: "Quagsire", NameCN: "沼王", Type1: "Water", Type2: "Ground",},
	{NationalNo: 196, Name: "Espeon", NameCN: "太阳伊布", Type1: "Psychic", },
	{NationalNo: 197, Name: "Umbreon", NameCN: "月亮伊布", Type1: "Dark", },
	{NationalNo: 198, Name: "Murkrow", NameCN: "黑暗鸦", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 199, Name: "Slowking", NameCN: "呆呆王", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 200, Name: "Misdreavus", NameCN: "梦妖", Type1: "Ghost", },
	{NationalNo: 201, Name: "Unown", NameCN: "未知图腾", Type1: "Psychic", },
	{NationalNo: 202, Name: "Wobbuffet", NameCN: "果然翁", Type1: "Psychic", },
	{NationalNo: 203, Name: "Girafarig", NameCN: "麒麟奇", Type1: "Normal", Type2: "Psychic",},
	{NationalNo: 204, Name: "Pineco", NameCN: "榛果球", Type1: "Bug", },
	{NationalNo: 205, Name: "Forretress", NameCN: "佛烈托斯", Type1: "Bug", Type2: "Steel",},
	{NationalNo: 206, Name: "Dunsparce", NameCN: "土龙弟弟", Type1: "Normal", },
	{NationalNo: 207, Name: "Gligar", NameCN: "天蝎", Type1: "Ground", Type2: "Flying",},
	{NationalNo: 208, Name: "Steelix", NameCN: "大钢蛇", Type1: "Steel", Type2: "Ground",},
	{NationalNo: 209, Name: "Snubbull", NameCN: "布鲁", Type1: "Fairy", },
	{NationalNo: 210, Name: "Granbull", NameCN: "布鲁皇", Type1: "Fairy", },
	{NationalNo: 211, Name: "Qwilfish", NameCN: "千针鱼", Type1: "Water", Type2: "Poison",},
	{NationalNo: 212, Name: "Scizor", NameCN: "巨钳螳螂", Type1: "Bug", Type2: "Steel",},
	{NationalNo: 213, Name: "Shuckle", NameCN: "壶壶", Type1: "Bug", Type2: "Rock",},
	{NationalNo: 214, Name: "Heracross", NameCN: "赫拉克罗斯", Type1: "Bug", Type2: "Fighting",},
	{NationalNo: 215, Name: "Sneasel", NameCN: "狃拉", Type1: "Dark", Type2: "Ice",},
	{NationalNo: 216, Name: "Teddiursa", NameCN: "熊宝宝", Type1: "Normal", },
	{NationalNo: 217, Name: "Ursaring", NameCN: "圈圈熊", Type1: "Normal", },
	{NationalNo: 218, Name: "Slugma", NameCN: "熔岩虫", Type1: "Fire", },
	{NationalNo: 219, Name: "Magcargo", NameCN: "熔岩蜗牛", Type1: "Fire", Type2: "Rock",},
	{NationalNo: 220, Name: "Swinub", NameCN: "小山猪", Type1: "Ice", Type2: "Ground",},
	{NationalNo: 221, Name: "Piloswine", NameCN: "长毛猪", Type1: "Ice", Type2: "Ground",},
	{NationalNo: 222, Name: "Corsola", NameCN: "太阳珊瑚", Type1: "Water", Type2: "Rock",},
	{NationalNo: 223, Name: "Remoraid", NameCN: "铁炮鱼", Type1: "Water", },
	{NationalNo: 224, Name: "Octillery", NameCN: "章鱼桶", Type1: "Water", },
	{NationalNo: 225, Name: "Delibird", NameCN: "信使鸟", Type1: "Ice", Type2: "Flying",},
	{NationalNo: 226, Name: "Mantine", NameCN: "巨翅飞鱼", Type1: "Water", Type2: "Flying",},
	{NationalNo: 227, Name: "Skarmory", NameCN: "盔甲鸟", Type1: "Steel", Type2: "Flying",},
	{NationalNo: 228, Name: "Houndour", NameCN: "戴鲁比", Type1: "Dark", Type2: "Fire",},
	{NationalNo: 229, Name: "Houndoom", NameCN: "黑鲁加", Type1: "Dark", Type2: "Fire",},
	{NationalNo: 230, Name: "Kingdra", NameCN: "刺龙王", Type1: "Water", Type2: "Dragon",},
	{NationalNo: 231, Name: "Phanpy", NameCN: "小小象", Type1: "Ground", },
	{NationalNo: 232, Name: "Donphan", NameCN: "顿甲", Type1: "Ground", },
	{NationalNo: 233, Name: "Porygon2", NameCN: "多边兽Ⅱ", Type1: "Normal", },
	{NationalNo: 234, Name: "Stantler", NameCN: "惊角鹿", Type1: "Normal", },
	{NationalNo: 235, Name: "Smeargle", NameCN: "图图犬", Type1: "Normal", },
	{NationalNo: 236, Name: "Tyrogue", NameCN: "无畏小子", Type1: "Fighting", },
	{NationalNo: 237, Name: "Hitmontop", NameCN: "战舞郎", Type1: "Fighting", },
	{NationalNo: 238, Name: "Smoochum", NameCN: "迷唇娃", Type1: "Ice", Type2: "Psychic",},
	{NationalNo: 239, Name: "Elekid", NameCN: "电击怪", Type1: "Electric", },
	{NationalNo: 240, Name: "Magby", NameCN: "鸭嘴宝宝", Type1: "Fire", },
	{NationalNo: 241, Name: "Miltank", NameCN: "大奶罐", Type1: "Normal", },
	{NationalNo: 242, Name: "Blissey", NameCN: "幸福蛋", Type1: "Normal", },
	{NationalNo: 243, Name: "Raikou", NameCN: "雷公", Type1: "Electric", },
	{NationalNo: 244, Name: "Entei", NameCN: "炎帝", Type1: "Fire", },
	{NationalNo: 245, Name: "Suicune", NameCN: "水君", Type1: "Water", },
	{NationalNo: 246, Name: "Larvitar", NameCN: "幼基拉斯", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 247, Name: "Pupitar", NameCN: "沙基拉斯", Type1: "Rock", Type2: "Ground",},
	{NationalNo: 248, Name: "Tyranitar", NameCN: "班基拉斯", Type1: "Rock", Type2: "Dark",},
	{NationalNo: 249, Name: "Lugia", NameCN: "洛奇亚", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 250, Name: "Ho-Oh", NameCN: "凤王", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 251, Name: "Celebi", NameCN: "时拉比", Type1: "Psychic", Type2: "Grass",},
	{NationalNo: 252, Name: "Treecko", NameCN: "木守宫", Type1: "Grass", },
	{NationalNo: 253, Name: "Grovyle", NameCN: "森林蜥蜴", Type1: "Grass", },
	{NationalNo: 254, Name: "Sceptile", NameCN: "蜥蜴王", Type1: "Grass", },
	{NationalNo: 255, Name: "Torchic", NameCN: "火稚鸡", Type1: "Fire", },
	{NationalNo: 256, Name: "Combusken", NameCN: "力壮鸡", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 257, Name: "Blaziken", NameCN: "火焰鸡", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 258, Name: "Mudkip", NameCN: "水跃鱼", Type1: "Water", },
	{NationalNo: 259, Name: "Marshtomp", NameCN: "沼跃鱼", Type1: "Water", Type2: "Ground",},
	{NationalNo: 260, Name: "Swampert", NameCN: "巨沼怪", Type1: "Water", Type2: "Ground",},
	{NationalNo: 261, Name: "Poochyena", NameCN: "土狼犬", Type1: "Dark", },
	{NationalNo: 262, Name: "Mightyena", NameCN: "大狼犬", Type1: "Dark", },
	{NationalNo: 263, Name: "Zigzagoon", NameCN: "蛇纹熊", Type1: "Normal", },
	{NationalNo: 264, Name: "Linoone", NameCN: "直冲熊", Type1: "Normal", },
	{NationalNo: 265, Name: "Wurmple", NameCN: "刺尾虫", Type1: "Bug", },
	{NationalNo: 266, Name: "Silcoon", NameCN: "甲壳茧", Type1: "Bug", },
	{NationalNo: 267, Name: "Beautifly", NameCN: "狩猎凤蝶", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 268, Name: "Cascoon", NameCN: "盾甲茧", Type1: "Bug", },
	{NationalNo: 269, Name: "Dustox", NameCN: "毒粉蛾", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 270, Name: "Lotad", NameCN: "莲叶童子", Type1: "Water", Type2: "Grass",},
	{NationalNo: 271, Name: "Lombre", NameCN: "莲帽小童", Type1: "Water", Type2: "Grass",},
	{NationalNo: 272, Name: "Ludicolo", NameCN: "乐天河童", Type1: "Water", Type2: "Grass",},
	{NationalNo: 273, Name: "Seedot", NameCN: "橡实果", Type1: "Grass", },
	{NationalNo: 274, Name: "Nuzleaf", NameCN: "长鼻叶", Type1: "Grass", Type2: "Dark",},
	{NationalNo: 275, Name: "Shiftry", NameCN: "狡猾天狗", Type1: "Grass", Type2: "Dark",},
	{NationalNo: 276, Name: "Taillow", NameCN: "傲骨燕", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 277, Name: "Swellow", NameCN: "大王燕", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 278, Name: "Wingull", NameCN: "长翅鸥", Type1: "Water", Type2: "Flying",},
	{NationalNo: 279, Name: "Pelipper", NameCN: "大嘴鸥", Type1: "Water", Type2: "Flying",},
	{NationalNo: 280, Name: "Ralts", NameCN: "拉鲁拉丝", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 281, Name: "Kirlia", NameCN: "奇鲁莉安", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 282, Name: "Gardevoir", NameCN: "沙奈朵", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 283, Name: "Surskit", NameCN: "溜溜糖球", Type1: "Bug", Type2: "Water",},
	{NationalNo: 284, Name: "Masquerain", NameCN: "雨翅蛾", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 285, Name: "Shroomish", NameCN: "蘑蘑菇", Type1: "Grass", },
	{NationalNo: 286, Name: "Breloom", NameCN: "斗笠菇", Type1: "Grass", Type2: "Fighting",},
	{NationalNo: 287, Name: "Slakoth", NameCN: "懒人獭", Type1: "Normal", },
	{NationalNo: 288, Name: "Vigoroth", NameCN: "过动猿", Type1: "Normal", },
	{NationalNo: 289, Name: "Slaking", NameCN: "请假王", Type1: "Normal", },
	{NationalNo: 290, Name: "Nincada", NameCN: "土居忍士", Type1: "Bug", Type2: "Ground",},
	{NationalNo: 291, Name: "Ninjask", NameCN: "铁面忍者", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 292, Name: "Shedinja", NameCN: "脱壳忍者", Type1: "Bug", Type2: "Ghost",},
	{NationalNo: 293, Name: "Whismur", NameCN: "咕妞妞", Type1: "Normal", },
	{NationalNo: 294, Name: "Loudred", NameCN: "吼爆弹", Type1: "Normal", },
	{NationalNo: 295, Name: "Exploud", NameCN: "爆音怪", Type1: "Normal", },
	{NationalNo: 296, Name: "Makuhita", NameCN: "幕下力士", Type1: "Fighting", },
	{NationalNo: 297, Name: "Hariyama", NameCN: "铁掌力士", Type1: "Fighting", },
	{NationalNo: 298, Name: "Azurill", NameCN: "露力丽", Type1: "Normal", Type2: "Fairy",},
	{NationalNo: 299, Name: "Nosepass", NameCN: "朝北鼻", Type1: "Rock", },
	{NationalNo: 300, Name: "Skitty", NameCN: "向尾喵", Type1: "Normal", },
	{NationalNo: 301, Name: "Delcatty", NameCN: "优雅猫", Type1: "Normal", },
	{NationalNo: 302, Name: "Sableye", NameCN: "勾魂眼", Type1: "Dark", Type2: "Ghost",},
	{NationalNo: 303, Name: "Mawile", NameCN: "大嘴娃", Type1: "Steel", Type2: "Fairy",},
	{NationalNo: 304, Name: "Aron", NameCN: "可可多拉", Type1: "Steel", Type2: "Rock",},
	{NationalNo: 305, Name: "Lairon", NameCN: "可多拉", Type1: "Steel", Type2: "Rock",},
	{NationalNo: 306, Name: "Aggron", NameCN: "波士可多拉", Type1: "Steel", Type2: "Rock",},
	{NationalNo: 307, Name: "Meditite", NameCN: "玛沙那", Type1: "Fighting", Type2: "Psychic",},
	{NationalNo: 308, Name: "Medicham", NameCN: "恰雷姆", Type1: "Fighting", Type2: "Psychic",},
	{NationalNo: 309, Name: "Electrike", NameCN: "落雷兽", Type1: "Electric", },
	{NationalNo: 310, Name: "Manectric", NameCN: "雷电兽", Type1: "Electric", },
	{NationalNo: 311, Name: "Plusle", NameCN: "正电拍拍", Type1: "Electric", },
	{NationalNo: 312, Name: "Minun", NameCN: "负电拍拍", Type1: "Electric", },
	{NationalNo: 313, Name: "Volbeat", NameCN: "电萤虫", Type1: "Bug", },
	{NationalNo: 314, Name: "Illumise", NameCN: "甜甜萤", Type1: "Bug", },
	{NationalNo: 315, Name: "Roselia", NameCN: "毒蔷薇", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 316, Name: "Gulpin", NameCN: "溶食兽", Type1: "Poison", },
	{NationalNo: 317, Name: "Swalot", NameCN: "吞食兽", Type1: "Poison", },
	{NationalNo: 318, Name: "Carvanha", NameCN: "利牙鱼", Type1: "Water", Type2: "Dark",},
	{NationalNo: 319, Name: "Sharpedo", NameCN: "巨牙鲨", Type1: "Water", Type2: "Dark",},
	{NationalNo: 320, Name: "Wailmer", NameCN: "吼吼鲸", Type1: "Water", },
	{NationalNo: 321, Name: "Wailord", NameCN: "吼鲸王", Type1: "Water", },
	{NationalNo: 322, Name: "Numel", NameCN: "呆火驼", Type1: "Fire", Type2: "Ground",},
	{NationalNo: 323, Name: "Camerupt", NameCN: "喷火驼", Type1: "Fire", Type2: "Ground",},
	{NationalNo: 324, Name: "Torkoal", NameCN: "煤炭龟", Type1: "Fire", },
	{NationalNo: 325, Name: "Spoink", NameCN: "跳跳猪", Type1: "Psychic", },
	{NationalNo: 326, Name: "Grumpig", NameCN: "噗噗猪", Type1: "Psychic", },
	{NationalNo: 327, Name: "Spinda", NameCN: "晃晃斑", Type1: "Normal", },
	{NationalNo: 328, Name: "Trapinch", NameCN: "大颚蚁", Type1: "Ground", },
	{NationalNo: 329, Name: "Vibrava", NameCN: "超音波幼虫", Type1: "Ground", Type2: "Dragon",},
	{NationalNo: 330, Name: "Flygon", NameCN: "沙漠蜻蜓", Type1: "Ground", Type2: "Dragon",},
	{NationalNo: 331, Name: "Cacnea", NameCN: "刺球仙人掌", Type1: "Grass", },
	{NationalNo: 332, Name: "Cacturne", NameCN: "梦歌仙人掌", Type1: "Grass", Type2: "Dark",},
	{NationalNo: 333, Name: "Swablu", NameCN: "青绵鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 334, Name: "Altaria", NameCN: "七夕青鸟", Type1: "Dragon", Type2: "Flying",},
	{NationalNo: 335, Name: "Zangoose", NameCN: "猫鼬斩", Type1: "Normal", },
	{NationalNo: 336, Name: "Seviper", NameCN: "饭匙蛇", Type1: "Poison", },
	{NationalNo: 337, Name: "Lunatone", NameCN: "月石", Type1: "Rock", Type2: "Psychic",},
	{NationalNo: 338, Name: "Solrock", NameCN: "太阳岩", Type1: "Rock", Type2: "Psychic",},
	{NationalNo: 339, Name: "Barboach", NameCN: "泥泥鳅", Type1: "Water", Type2: "Ground",},
	{NationalNo: 340, Name: "Whiscash", NameCN: "鲶鱼王", Type1: "Water", Type2: "Ground",},
	{NationalNo: 341, Name: "Corphish", NameCN: "龙虾小兵", Type1: "Water", },
	{NationalNo: 342, Name: "Crawdaunt", NameCN: "铁螯龙虾", Type1: "Water", Type2: "Dark",},
	{NationalNo: 343, Name: "Baltoy", NameCN: "天秤偶", Type1: "Ground", Type2: "Psychic",},
	{NationalNo: 344, Name: "Claydol", NameCN: "念力土偶", Type1: "Ground", Type2: "Psychic",},
	{NationalNo: 345, Name: "Lileep", NameCN: "触手百合", Type1: "Rock", Type2: "Grass",},
	{NationalNo: 346, Name: "Cradily", NameCN: "摇篮百合", Type1: "Rock", Type2: "Grass",},
	{NationalNo: 347, Name: "Anorith", NameCN: "太古羽虫", Type1: "Rock", Type2: "Bug",},
	{NationalNo: 348, Name: "Armaldo", NameCN: "太古盔甲", Type1: "Rock", Type2: "Bug",},
	{NationalNo: 349, Name: "Feebas", NameCN: "丑丑鱼", Type1: "Water", },
	{NationalNo: 350, Name: "Milotic", NameCN: "美纳斯", Type1: "Water", },
	{NationalNo: 351, Name: "Castform", NameCN: "飘浮泡泡", Type1: "Normal", },
	{NationalNo: 352, Name: "Kecleon", NameCN: "变隐龙", Type1: "Normal", },
	{NationalNo: 353, Name: "Shuppet", NameCN: "怨影娃娃", Type1: "Ghost", },
	{NationalNo: 354, Name: "Banette", NameCN: "诅咒娃娃", Type1: "Ghost", },
	{NationalNo: 355, Name: "Duskull", NameCN: "夜巡灵", Type1: "Ghost", },
	{NationalNo: 356, Name: "Dusclops", NameCN: "彷徨夜灵", Type1: "Ghost", },
	{NationalNo: 357, Name: "Tropius", NameCN: "热带龙", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 358, Name: "Chimecho", NameCN: "风铃铃", Type1: "Psychic", },
	{NationalNo: 359, Name: "Absol", NameCN: "阿勃梭鲁", Type1: "Dark", },
	{NationalNo: 360, Name: "Wynaut", NameCN: "小果然", Type1: "Psychic", },
	{NationalNo: 361, Name: "Snorunt", NameCN: "雪童子", Type1: "Ice", },
	{NationalNo: 362, Name: "Glalie", NameCN: "冰鬼护", Type1: "Ice", },
	{NationalNo: 363, Name: "Spheal", NameCN: "海豹球", Type1: "Ice", Type2: "Water",},
	{NationalNo: 364, Name: "Sealeo", NameCN: "海魔狮", Type1: "Ice", Type2: "Water",},
	{NationalNo: 365, Name: "Walrein", NameCN: "帝牙海狮", Type1: "Ice", Type2: "Water",},
	{NationalNo: 366, Name: "Clamperl", NameCN: "珍珠贝", Type1: "Water", },
	{NationalNo: 367, Name: "Huntail", NameCN: "猎斑鱼", Type1: "Water", },
	{NationalNo: 368, Name: "Gorebyss", NameCN: "樱花鱼", Type1: "Water", },
	{NationalNo: 369, Name: "Relicanth", NameCN: "古空棘鱼", Type1: "Water", Type2: "Rock",},
	{NationalNo: 370, Name: "Luvdisc", NameCN: "爱心鱼", Type1: "Water", },
	{NationalNo: 371, Name: "Bagon", NameCN: "宝贝龙", Type1: "Dragon", },
	{NationalNo: 372, Name: "Shelgon", NameCN: "甲壳龙", Type1: "Dragon", },
	{NationalNo: 373, Name: "Salamence", NameCN: "暴飞龙", Type1: "Dragon", Type2: "Flying",},
	{NationalNo: 374, Name: "Beldum", NameCN: "铁哑铃", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 375, Name: "Metang", NameCN: "金属怪", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 376, Name: "Metagross", NameCN: "巨金怪", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 377, Name: "Regirock", NameCN: "雷吉洛克", Type1: "Rock", },
	{NationalNo: 378, Name: "Regice", NameCN: "雷吉艾斯", Type1: "Ice", },
	{NationalNo: 379, Name: "Registeel", NameCN: "雷吉斯奇鲁", Type1: "Steel", },
	{NationalNo: 380, Name: "Latias", NameCN: "拉帝亚斯", Type1: "Dragon", Type2: "Psychic",},
	{NationalNo: 381, Name: "Latios", NameCN: "拉帝欧斯", Type1: "Dragon", Type2: "Psychic",},
	{NationalNo: 382, Name: "Kyogre", NameCN: "盖欧卡", Type1: "Water", },
	{NationalNo: 383, Name: "Groudon", NameCN: "固拉多", Type1: "Ground", },
	{NationalNo: 384, Name: "Rayquaza", NameCN: "烈空坐", Type1: "Dragon", Type2: "Flying",},
	{NationalNo: 385, Name: "Jirachi", NameCN: "基拉祈", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 386, Name: "Deoxys", NameCN: "代欧奇希斯", Type1: "Psychic", },
	{NationalNo: 387, Name: "Turtwig", NameCN: "草苗龟", Type1: "Grass", },
	{NationalNo: 388, Name: "Grotle", NameCN: "树林龟", Type1: "Grass", },
	{NationalNo: 389, Name: "Torterra", NameCN: "土台龟", Type1: "Grass", Type2: "Ground",},
	{NationalNo: 390, Name: "Chimchar", NameCN: "小火焰猴", Type1: "Fire", },
	{NationalNo: 391, Name: "Monferno", NameCN: "猛火猴", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 392, Name: "Infernape", NameCN: "烈焰猴", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 393, Name: "Piplup", NameCN: "波加曼", Type1: "Water", },
	{NationalNo: 394, Name: "Prinplup", NameCN: "波皇子", Type1: "Water", },
	{NationalNo: 395, Name: "Empoleon", NameCN: "帝王拿波", Type1: "Water", Type2: "Steel",},
	{NationalNo: 396, Name: "Starly", NameCN: "姆克儿", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 397, Name: "Staravia", NameCN: "姆克鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 398, Name: "Staraptor", NameCN: "姆克鹰", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 399, Name: "Bidoof", NameCN: "大牙狸", Type1: "Normal", },
	{NationalNo: 400, Name: "Bibarel", NameCN: "大尾狸", Type1: "Normal", Type2: "Water",},
	{NationalNo: 401, Name: "Kricketot", NameCN: "圆法师", Type1: "Bug", },
	{NationalNo: 402, Name: "Kricketune", NameCN: "音箱蟀", Type1: "Bug", },
	{NationalNo: 403, Name: "Shinx", NameCN: "小猫怪", Type1: "Electric", },
	{NationalNo: 404, Name: "Luxio", NameCN: "勒克猫", Type1: "Electric", },
	{NationalNo: 405, Name: "Luxray", NameCN: "伦琴猫", Type1: "Electric", },
	{NationalNo: 406, Name: "Budew", NameCN: "含羞苞", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 407, Name: "Roserade", NameCN: "罗丝雷朵", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 408, Name: "Cranidos", NameCN: "头盖龙", Type1: "Rock", },
	{NationalNo: 409, Name: "Rampardos", NameCN: "战槌龙", Type1: "Rock", },
	{NationalNo: 410, Name: "Shieldon", NameCN: "盾甲龙", Type1: "Rock", Type2: "Steel",},
	{NationalNo: 411, Name: "Bastiodon", NameCN: "护城龙", Type1: "Rock", Type2: "Steel",},
	{NationalNo: 412, Name: "Burmy", NameCN: "结草儿", Type1: "Bug", },
	{NationalNo: 413, Name: "Wormadam", NameCN: "结草贵妇", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 414, Name: "Mothim", NameCN: "绅士蛾", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 415, Name: "Combee", NameCN: "三蜜蜂", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 416, Name: "Vespiquen", NameCN: "蜂女王", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 417, Name: "Pachirisu", NameCN: "帕奇利兹", Type1: "Electric", },
	{NationalNo: 418, Name: "Buizel", NameCN: "泳圈鼬", Type1: "Water", },
	{NationalNo: 419, Name: "Floatzel", NameCN: "浮潜鼬", Type1: "Water", },
	{NationalNo: 420, Name: "Cherubi", NameCN: "樱花宝", Type1: "Grass", },
	{NationalNo: 421, Name: "Cherrim", NameCN: "樱花儿", Type1: "Grass", },
	{NationalNo: 422, Name: "Shellos", NameCN: "无壳海兔", Type1: "Water", },
	{NationalNo: 423, Name: "Gastrodon", NameCN: "海兔兽", Type1: "Water", Type2: "Ground",},
	{NationalNo: 424, Name: "Ambipom", NameCN: "双尾怪手", Type1: "Normal", },
	{NationalNo: 425, Name: "Drifloon", NameCN: "飘飘球", Type1: "Ghost", Type2: "Flying",},
	{NationalNo: 426, Name: "Drifblim", NameCN: "随风球", Type1: "Ghost", Type2: "Flying",},
	{NationalNo: 427, Name: "Buneary", NameCN: "卷卷耳", Type1: "Normal", },
	{NationalNo: 428, Name: "Lopunny", NameCN: "长耳兔", Type1: "Normal", },
	{NationalNo: 429, Name: "Mismagius", NameCN: "梦妖魔", Type1: "Ghost", },
	{NationalNo: 430, Name: "Honchkrow", NameCN: "乌鸦头头", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 431, Name: "Glameow", NameCN: "魅力喵", Type1: "Normal", },
	{NationalNo: 432, Name: "Purugly", NameCN: "东施喵", Type1: "Normal", },
	{NationalNo: 433, Name: "Chingling", NameCN: "铃铛响", Type1: "Psychic", },
	{NationalNo: 434, Name: "Stunky", NameCN: "臭鼬噗", Type1: "Poison", Type2: "Dark",},
	{NationalNo: 435, Name: "Skuntank", NameCN: "坦克臭鼬", Type1: "Poison", Type2: "Dark",},
	{NationalNo: 436, Name: "Bronzor", NameCN: "铜镜怪", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 437, Name: "Bronzong", NameCN: "青铜钟", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 438, Name: "Bonsly", NameCN: "盆才怪", Type1: "Rock", },
	{NationalNo: 439, Name: "Mime Jr.", NameCN: "魔尼尼", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 440, Name: "Happiny", NameCN: "小福蛋", Type1: "Normal", },
	{NationalNo: 441, Name: "Chatot", NameCN: "聒噪鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 442, Name: "Spiritomb", NameCN: "花岩怪", Type1: "Ghost", Type2: "Dark",},
	{NationalNo: 443, Name: "Gible", NameCN: "圆陆鲨", Type1: "Dragon", Type2: "Ground",},
	{NationalNo: 444, Name: "Gabite", NameCN: "尖牙陆鲨", Type1: "Dragon", Type2: "Ground",},
	{NationalNo: 445, Name: "Garchomp", NameCN: "烈咬陆鲨", Type1: "Dragon", Type2: "Ground",},
	{NationalNo: 446, Name: "Munchlax", NameCN: "小卡比兽", Type1: "Normal", },
	{NationalNo: 447, Name: "Riolu", NameCN: "利欧路", Type1: "Fighting", },
	{NationalNo: 448, Name: "Lucario", NameCN: "路卡利欧", Type1: "Fighting", Type2: "Steel",},
	{NationalNo: 449, Name: "Hippopotas", NameCN: "沙河马", Type1: "Ground", },
	{NationalNo: 450, Name: "Hippowdon", NameCN: "河马兽", Type1: "Ground", },
	{NationalNo: 451, Name: "Skorupi", NameCN: "钳尾蝎", Type1: "Poison", Type2: "Bug",},
	{NationalNo: 452, Name: "Drapion", NameCN: "龙王蝎", Type1: "Poison", Type2: "Dark",},
	{NationalNo: 453, Name: "Croagunk", NameCN: "不良蛙", Type1: "Poison", Type2: "Fighting",},
	{NationalNo: 454, Name: "Toxicroak", NameCN: "毒骷蛙", Type1: "Poison", Type2: "Fighting",},
	{NationalNo: 455, Name: "Carnivine", NameCN: "尖牙笼", Type1: "Grass", },
	{NationalNo: 456, Name: "Finneon", NameCN: "荧光鱼", Type1: "Water", },
	{NationalNo: 457, Name: "Lumineon", NameCN: "霓虹鱼", Type1: "Water", },
	{NationalNo: 458, Name: "Mantyke", NameCN: "小球飞鱼", Type1: "Water", Type2: "Flying",},
	{NationalNo: 459, Name: "Snover", NameCN: "雪笠怪", Type1: "Grass", Type2: "Ice",},
	{NationalNo: 460, Name: "Abomasnow", NameCN: "暴雪王", Type1: "Grass", Type2: "Ice",},
	{NationalNo: 461, Name: "Weavile", NameCN: "玛狃拉", Type1: "Dark", Type2: "Ice",},
	{NationalNo: 462, Name: "Magnezone", NameCN: "自爆磁怪", Type1: "Electric", Type2: "Steel",},
	{NationalNo: 463, Name: "Lickilicky", NameCN: "大舌舔", Type1: "Normal", },
	{NationalNo: 464, Name: "Rhyperior", NameCN: "超甲狂犀", Type1: "Ground", Type2: "Rock",},
	{NationalNo: 465, Name: "Tangrowth", NameCN: "巨蔓藤", Type1: "Grass", },
	{NationalNo: 466, Name: "Electivire", NameCN: "电击魔兽", Type1: "Electric", },
	{NationalNo: 467, Name: "Magmortar", NameCN: "鸭嘴炎兽", Type1: "Fire", },
	{NationalNo: 468, Name: "Togekiss", NameCN: "波克基斯", Type1: "Fairy", Type2: "Flying",},
	{NationalNo: 469, Name: "Yanmega", NameCN: "远古巨蜓", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 470, Name: "Leafeon", NameCN: "叶伊布", Type1: "Grass", },
	{NationalNo: 471, Name: "Glaceon", NameCN: "冰伊布", Type1: "Ice", },
	{NationalNo: 472, Name: "Gliscor", NameCN: "天蝎王", Type1: "Ground", Type2: "Flying",},
	{NationalNo: 473, Name: "Mamoswine", NameCN: "象牙猪", Type1: "Ice", Type2: "Ground",},
	{NationalNo: 474, Name: "Porygon-Z", NameCN: "多边兽Ｚ", Type1: "Normal", },
	{NationalNo: 475, Name: "Gallade", NameCN: "艾路雷朵", Type1: "Psychic", Type2: "Fighting",},
	{NationalNo: 476, Name: "Probopass", NameCN: "大朝北鼻", Type1: "Rock", Type2: "Steel",},
	{NationalNo: 477, Name: "Dusknoir", NameCN: "黑夜魔灵", Type1: "Ghost", },
	{NationalNo: 478, Name: "Froslass", NameCN: "雪妖女", Type1: "Ice", Type2: "Ghost",},
	{NationalNo: 479, Name: "Rotom", NameCN: "洛托姆", Type1: "Electric", Type2: "Ghost",},
	{NationalNo: 480, Name: "Uxie", NameCN: "由克希", Type1: "Psychic", },
	{NationalNo: 481, Name: "Mesprit", NameCN: "艾姆利多", Type1: "Psychic", },
	{NationalNo: 482, Name: "Azelf", NameCN: "亚克诺姆", Type1: "Psychic", },
	{NationalNo: 483, Name: "Dialga", NameCN: "帝牙卢卡", Type1: "Steel", Type2: "Dragon",},
	{NationalNo: 484, Name: "Palkia", NameCN: "帕路奇亚", Type1: "Water", Type2: "Dragon",},
	{NationalNo: 485, Name: "Heatran", NameCN: "席多蓝恩", Type1: "Fire", Type2: "Steel",},
	{NationalNo: 486, Name: "Regigigas", NameCN: "雷吉奇卡斯", Type1: "Normal", },
	{NationalNo: 487, Name: "Giratina", NameCN: "骑拉帝纳", Type1: "Ghost", Type2: "Dragon",},
	{NationalNo: 488, Name: "Cresselia", NameCN: "克雷色利亚", Type1: "Psychic", },
	{NationalNo: 489, Name: "Phione", NameCN: "霏欧纳", Type1: "Water", },
	{NationalNo: 490, Name: "Manaphy", NameCN: "玛纳霏", Type1: "Water", },
	{NationalNo: 491, Name: "Darkrai", NameCN: "达克莱伊", Type1: "Dark", },
	{NationalNo: 492, Name: "Shaymin", NameCN: "谢米", Type1: "Grass", },
	{NationalNo: 493, Name: "Arceus", NameCN: "阿尔宙斯", Type1: "Normal", },
	{NationalNo: 494, Name: "Victini", NameCN: "比克提尼", Type1: "Psychic", Type2: "Fire",},
	{NationalNo: 495, Name: "Snivy", NameCN: "藤藤蛇", Type1: "Grass", },
	{NationalNo: 496, Name: "Servine", NameCN: "青藤蛇", Type1: "Grass", },
	{NationalNo: 497, Name: "Serperior", NameCN: "君主蛇", Type1: "Grass", },
	{NationalNo: 498, Name: "Tepig", NameCN: "暖暖猪", Type1: "Fire", },
	{NationalNo: 499, Name: "Pignite", NameCN: "炒炒猪", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 500, Name: "Emboar", NameCN: "炎武王", Type1: "Fire", Type2: "Fighting",},
	{NationalNo: 501, Name: "Oshawott", NameCN: "水水獭", Type1: "Water", },
	{NationalNo: 502, Name: "Dewott", NameCN: "双刃丸", Type1: "Water", },
	{NationalNo: 503, Name: "Samurott", NameCN: "大剑鬼", Type1: "Water", },
	{NationalNo: 504, Name: "Patrat", NameCN: "探探鼠", Type1: "Normal", },
	{NationalNo: 505, Name: "Watchog", NameCN: "步哨鼠", Type1: "Normal", },
	{NationalNo: 506, Name: "Lillipup", NameCN: "小约克", Type1: "Normal", },
	{NationalNo: 507, Name: "Herdier", NameCN: "哈约克", Type1: "Normal", },
	{NationalNo: 508, Name: "Stoutland", NameCN: "长毛狗", Type1: "Normal", },
	{NationalNo: 509, Name: "Purrloin", NameCN: "扒手猫", Type1: "Dark", },
	{NationalNo: 510, Name: "Liepard", NameCN: "酷豹", Type1: "Dark", },
	{NationalNo: 511, Name: "Pansage", NameCN: "花椰猴", Type1: "Grass", },
	{NationalNo: 512, Name: "Simisage", NameCN: "花椰猿", Type1: "Grass", },
	{NationalNo: 513, Name: "Pansear", NameCN: "爆香猴", Type1: "Fire", },
	{NationalNo: 514, Name: "Simisear", NameCN: "爆香猿", Type1: "Fire", },
	{NationalNo: 515, Name: "Panpour", NameCN: "冷水猴", Type1: "Water", },
	{NationalNo: 516, Name: "Simipour", NameCN: "冷水猿", Type1: "Water", },
	{NationalNo: 517, Name: "Munna", NameCN: "食梦梦", Type1: "Psychic", },
	{NationalNo: 518, Name: "Musharna", NameCN: "梦梦蚀", Type1: "Psychic", },
	{NationalNo: 519, Name: "Pidove", NameCN: "豆豆鸽", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 520, Name: "Tranquill", NameCN: "咕咕鸽", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 521, Name: "Unfezant", NameCN: "高傲雉鸡", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 522, Name: "Blitzle", NameCN: "斑斑马", Type1: "Electric", },
	{NationalNo: 523, Name: "Zebstrika", NameCN: "雷电斑马", Type1: "Electric", },
	{NationalNo: 524, Name: "Roggenrola", NameCN: "石丸子", Type1: "Rock", },
	{NationalNo: 525, Name: "Boldore", NameCN: "地幔岩", Type1: "Rock", },
	{NationalNo: 526, Name: "Gigalith", NameCN: "庞岩怪", Type1: "Rock", },
	{NationalNo: 527, Name: "Woobat", NameCN: "滚滚蝙蝠", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 528, Name: "Swoobat", NameCN: "心蝙蝠", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 529, Name: "Drilbur", NameCN: "螺钉地鼠", Type1: "Ground", },
	{NationalNo: 530, Name: "Excadrill", NameCN: "龙头地鼠", Type1: "Ground", Type2: "Steel",},
	{NationalNo: 531, Name: "Audino", NameCN: "差不多娃娃", Type1: "Normal", },
	{NationalNo: 532, Name: "Timburr", NameCN: "搬运小匠", Type1: "Fighting", },
	{NationalNo: 533, Name: "Gurdurr", NameCN: "铁骨土人", Type1: "Fighting", },
	{NationalNo: 534, Name: "Conkeldurr", NameCN: "修建老匠", Type1: "Fighting", },
	{NationalNo: 535, Name: "Tympole", NameCN: "圆蝌蚪", Type1: "Water", },
	{NationalNo: 536, Name: "Palpitoad", NameCN: "蓝蟾蜍", Type1: "Water", Type2: "Ground",},
	{NationalNo: 537, Name: "Seismitoad", NameCN: "蟾蜍王", Type1: "Water", Type2: "Ground",},
	{NationalNo: 538, Name: "Throh", NameCN: "投摔鬼", Type1: "Fighting", },
	{NationalNo: 539, Name: "Sawk", NameCN: "打击鬼", Type1: "Fighting", },
	{NationalNo: 540, Name: "Sewaddle", NameCN: "虫宝包", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 541, Name: "Swadloon", NameCN: "宝包茧", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 542, Name: "Leavanny", NameCN: "保姆虫", Type1: "Bug", Type2: "Grass",},
	{NationalNo: 543, Name: "Venipede", NameCN: "百足蜈蚣", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 544, Name: "Whirlipede", NameCN: "车轮球", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 545, Name: "Scolipede", NameCN: "蜈蚣王", Type1: "Bug", Type2: "Poison",},
	{NationalNo: 546, Name: "Cottonee", NameCN: "木棉球", Type1: "Grass", Type2: "Fairy",},
	{NationalNo: 547, Name: "Whimsicott", NameCN: "风妖精", Type1: "Grass", Type2: "Fairy",},
	{NationalNo: 548, Name: "Petilil", NameCN: "百合根娃娃", Type1: "Grass", },
	{NationalNo: 549, Name: "Lilligant", NameCN: "裙儿小姐", Type1: "Grass", },
	{NationalNo: 550, Name: "Basculin", NameCN: "野蛮鲈鱼", Type1: "Water", },
	{NationalNo: 551, Name: "Sandile", NameCN: "黑眼鳄", Type1: "Ground", Type2: "Dark",},
	{NationalNo: 552, Name: "Krokorok", NameCN: "混混鳄", Type1: "Ground", Type2: "Dark",},
	{NationalNo: 553, Name: "Krookodile", NameCN: "流氓鳄", Type1: "Ground", Type2: "Dark",},
	{NationalNo: 554, Name: "Darumaka", NameCN: "火红不倒翁", Type1: "Fire", },
	{NationalNo: 555, Name: "Darmanitan", NameCN: "达摩狒狒", Type1: "Fire", },
	{NationalNo: 556, Name: "Maractus", NameCN: "沙铃仙人掌", Type1: "Grass", },
	{NationalNo: 557, Name: "Dwebble", NameCN: "石居蟹", Type1: "Bug", Type2: "Rock",},
	{NationalNo: 558, Name: "Crustle", NameCN: "岩殿居蟹", Type1: "Bug", Type2: "Rock",},
	{NationalNo: 559, Name: "Scraggy", NameCN: "滑滑小子", Type1: "Dark", Type2: "Fighting",},
	{NationalNo: 560, Name: "Scrafty", NameCN: "头巾混混", Type1: "Dark", Type2: "Fighting",},
	{NationalNo: 561, Name: "Sigilyph", NameCN: "象征鸟", Type1: "Psychic", Type2: "Flying",},
	{NationalNo: 562, Name: "Yamask", NameCN: "哭哭面具", Type1: "Ghost", },
	{NationalNo: 563, Name: "Cofagrigus", NameCN: "死神棺", Type1: "Ghost", },
	{NationalNo: 564, Name: "Tirtouga", NameCN: "原盖海龟", Type1: "Water", Type2: "Rock",},
	{NationalNo: 565, Name: "Carracosta", NameCN: "肋骨海龟", Type1: "Water", Type2: "Rock",},
	{NationalNo: 566, Name: "Archen", NameCN: "始祖小鸟", Type1: "Rock", Type2: "Flying",},
	{NationalNo: 567, Name: "Archeops", NameCN: "始祖大鸟", Type1: "Rock", Type2: "Flying",},
	{NationalNo: 568, Name: "Trubbish", NameCN: "破破袋", Type1: "Poison", },
	{NationalNo: 569, Name: "Garbodor", NameCN: "灰尘山", Type1: "Poison", },
	{NationalNo: 570, Name: "Zorua", NameCN: "索罗亚", Type1: "Dark", },
	{NationalNo: 571, Name: "Zoroark", NameCN: "索罗亚克", Type1: "Dark", },
	{NationalNo: 572, Name: "Minccino", NameCN: "泡沫栗鼠", Type1: "Normal", },
	{NationalNo: 573, Name: "Cinccino", NameCN: "奇诺栗鼠", Type1: "Normal", },
	{NationalNo: 574, Name: "Gothita", NameCN: "哥德宝宝", Type1: "Psychic", },
	{NationalNo: 575, Name: "Gothorita", NameCN: "哥德小童", Type1: "Psychic", },
	{NationalNo: 576, Name: "Gothitelle", NameCN: "哥德小姐", Type1: "Psychic", },
	{NationalNo: 577, Name: "Solosis", NameCN: "单卵细胞球", Type1: "Psychic", },
	{NationalNo: 578, Name: "Duosion", NameCN: "双卵细胞球", Type1: "Psychic", },
	{NationalNo: 579, Name: "Reuniclus", NameCN: "人造细胞卵", Type1: "Psychic", },
	{NationalNo: 580, Name: "Ducklett", NameCN: "鸭宝宝", Type1: "Water", Type2: "Flying",},
	{NationalNo: 581, Name: "Swanna", NameCN: "舞天鹅", Type1: "Water", Type2: "Flying",},
	{NationalNo: 582, Name: "Vanillite", NameCN: "迷你冰", Type1: "Ice", },
	{NationalNo: 583, Name: "Vanillish", NameCN: "多多冰", Type1: "Ice", },
	{NationalNo: 584, Name: "Vanilluxe", NameCN: "双倍多多冰", Type1: "Ice", },
	{NationalNo: 585, Name: "Deerling", NameCN: "四季鹿", Type1: "Normal", Type2: "Grass",},
	{NationalNo: 586, Name: "Sawsbuck", NameCN: "萌芽鹿", Type1: "Normal", Type2: "Grass",},
	{NationalNo: 587, Name: "Emolga", NameCN: "电飞鼠", Type1: "Electric", Type2: "Flying",},
	{NationalNo: 588, Name: "Karrablast", NameCN: "盖盖虫", Type1: "Bug", },
	{NationalNo: 589, Name: "Escavalier", NameCN: "骑士蜗牛", Type1: "Bug", Type2: "Steel",},
	{NationalNo: 590, Name: "Foongus", NameCN: "哎呀球菇", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 591, Name: "Amoonguss", NameCN: "败露球菇", Type1: "Grass", Type2: "Poison",},
	{NationalNo: 592, Name: "Frillish", NameCN: "轻飘飘", Type1: "Water", Type2: "Ghost",},
	{NationalNo: 593, Name: "Jellicent", NameCN: "胖嘟嘟", Type1: "Water", Type2: "Ghost",},
	{NationalNo: 594, Name: "Alomomola", NameCN: "保母曼波", Type1: "Water", },
	{NationalNo: 595, Name: "Joltik", NameCN: "电电虫", Type1: "Bug", Type2: "Electric",},
	{NationalNo: 596, Name: "Galvantula", NameCN: "电蜘蛛", Type1: "Bug", Type2: "Electric",},
	{NationalNo: 597, Name: "Ferroseed", NameCN: "种子铁球", Type1: "Grass", Type2: "Steel",},
	{NationalNo: 598, Name: "Ferrothorn", NameCN: "坚果哑铃", Type1: "Grass", Type2: "Steel",},
	{NationalNo: 599, Name: "Klink", NameCN: "齿轮儿", Type1: "Steel", },
	{NationalNo: 600, Name: "Klang", NameCN: "齿轮组", Type1: "Steel", },
	{NationalNo: 601, Name: "Klinklang", NameCN: "齿轮怪", Type1: "Steel", },
	{NationalNo: 602, Name: "Tynamo", NameCN: "麻麻小鱼", Type1: "Electric", },
	{NationalNo: 603, Name: "Eelektrik", NameCN: "麻麻鳗", Type1: "Electric", },
	{NationalNo: 604, Name: "Eelektross", NameCN: "麻麻鳗鱼王", Type1: "Electric", },
	{NationalNo: 605, Name: "Elgyem", NameCN: "小灰怪", Type1: "Psychic", },
	{NationalNo: 606, Name: "Beheeyem", NameCN: "大宇怪", Type1: "Psychic", },
	{NationalNo: 607, Name: "Litwick", NameCN: "烛光灵", Type1: "Ghost", Type2: "Fire",},
	{NationalNo: 608, Name: "Lampent", NameCN: "灯火幽灵", Type1: "Ghost", Type2: "Fire",},
	{NationalNo: 609, Name: "Chandelure", NameCN: "水晶灯火灵", Type1: "Ghost", Type2: "Fire",},
	{NationalNo: 610, Name: "Axew", NameCN: "牙牙", Type1: "Dragon", },
	{NationalNo: 611, Name: "Fraxure", NameCN: "斧牙龙", Type1: "Dragon", },
	{NationalNo: 612, Name: "Haxorus", NameCN: "双斧战龙", Type1: "Dragon", },
	{NationalNo: 613, Name: "Cubchoo", NameCN: "喷嚏熊", Type1: "Ice", },
	{NationalNo: 614, Name: "Beartic", NameCN: "冻原熊", Type1: "Ice", },
	{NationalNo: 615, Name: "Cryogonal", NameCN: "几何雪花", Type1: "Ice", },
	{NationalNo: 616, Name: "Shelmet", NameCN: "小嘴蜗", Type1: "Bug", },
	{NationalNo: 617, Name: "Accelgor", NameCN: "敏捷虫", Type1: "Bug", },
	{NationalNo: 618, Name: "Stunfisk", NameCN: "泥巴鱼", Type1: "Ground", Type2: "Electric",},
	{NationalNo: 619, Name: "Mienfoo", NameCN: "功夫鼬", Type1: "Fighting", },
	{NationalNo: 620, Name: "Mienshao", NameCN: "师父鼬", Type1: "Fighting", },
	{NationalNo: 621, Name: "Druddigon", NameCN: "赤面龙", Type1: "Dragon", },
	{NationalNo: 622, Name: "Golett", NameCN: "泥偶小人", Type1: "Ground", Type2: "Ghost",},
	{NationalNo: 623, Name: "Golurk", NameCN: "泥偶巨人", Type1: "Ground", Type2: "Ghost",},
	{NationalNo: 624, Name: "Pawniard", NameCN: "驹刀小兵", Type1: "Dark", Type2: "Steel",},
	{NationalNo: 625, Name: "Bisharp", NameCN: "劈斩司令", Type1: "Dark", Type2: "Steel",},
	{NationalNo: 626, Name: "Bouffalant", NameCN: "爆炸头水牛", Type1: "Normal", },
	{NationalNo: 627, Name: "Rufflet", NameCN: "毛头小鹰", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 628, Name: "Braviary", NameCN: "勇士雄鹰", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 629, Name: "Vullaby", NameCN: "秃鹰丫头", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 630, Name: "Mandibuzz", NameCN: "秃鹰娜", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 631, Name: "Heatmor", NameCN: "熔蚁兽", Type1: "Fire", },
	{NationalNo: 632, Name: "Durant", NameCN: "铁蚁", Type1: "Bug", Type2: "Steel",},
	{NationalNo: 633, Name: "Deino", NameCN: "单首龙", Type1: "Dark", Type2: "Dragon",},
	{NationalNo: 634, Name: "Zweilous", NameCN: "双首暴龙", Type1: "Dark", Type2: "Dragon",},
	{NationalNo: 635, Name: "Hydreigon", NameCN: "三首恶龙", Type1: "Dark", Type2: "Dragon",},
	{NationalNo: 636, Name: "Larvesta", NameCN: "燃烧虫", Type1: "Bug", Type2: "Fire",},
	{NationalNo: 637, Name: "Volcarona", NameCN: "火神蛾", Type1: "Bug", Type2: "Fire",},
	{NationalNo: 638, Name: "Cobalion", NameCN: "勾帕路翁", Type1: "Steel", Type2: "Fighting",},
	{NationalNo: 639, Name: "Terrakion", NameCN: "代拉基翁", Type1: "Rock", Type2: "Fighting",},
	{NationalNo: 640, Name: "Virizion", NameCN: "毕力吉翁", Type1: "Grass", Type2: "Fighting",},
	{NationalNo: 641, Name: "Tornadus", NameCN: "龙卷云", Type1: "Flying", },
	{NationalNo: 642, Name: "Thundurus", NameCN: "雷电云", Type1: "Electric", Type2: "Flying",},
	{NationalNo: 643, Name: "Reshiram", NameCN: "莱希拉姆", Type1: "Dragon", Type2: "Fire",},
	{NationalNo: 644, Name: "Zekrom", NameCN: "捷克罗姆", Type1: "Dragon", Type2: "Electric",},
	{NationalNo: 645, Name: "Landorus", NameCN: "土地云", Type1: "Ground", Type2: "Flying",},
	{NationalNo: 646, Name: "Kyurem", NameCN: "酋雷姆", Type1: "Dragon", Type2: "Ice",},
	{NationalNo: 647, Name: "Keldeo", NameCN: "凯路迪欧", Type1: "Water", Type2: "Fighting",},
	{NationalNo: 648, Name: "Meloetta", NameCN: "美洛耶塔", Type1: "Normal", Type2: "Psychic",},
	{NationalNo: 649, Name: "Genesect", NameCN: "盖诺赛克特", Type1: "Bug", Type2: "Steel",},
	{NationalNo: 650, Name: "Chespin", NameCN: "哈力栗", Type1: "Grass", },
	{NationalNo: 651, Name: "Quilladin", NameCN: "胖胖哈力", Type1: "Grass", },
	{NationalNo: 652, Name: "Chesnaught", NameCN: "布里卡隆", Type1: "Grass", Type2: "Fighting",},
	{NationalNo: 653, Name: "Fennekin", NameCN: "火狐狸", Type1: "Fire", },
	{NationalNo: 654, Name: "Braixen", NameCN: "长尾火狐", Type1: "Fire", },
	{NationalNo: 655, Name: "Delphox", NameCN: "妖火红狐", Type1: "Fire", Type2: "Psychic",},
	{NationalNo: 656, Name: "Froakie", NameCN: "呱呱泡蛙", Type1: "Water", },
	{NationalNo: 657, Name: "Frogadier", NameCN: "呱头蛙", Type1: "Water", },
	{NationalNo: 658, Name: "Greninja", NameCN: "甲贺忍蛙", Type1: "Water", Type2: "Dark",},
	{NationalNo: 659, Name: "Bunnelby", NameCN: "掘掘兔", Type1: "Normal", },
	{NationalNo: 660, Name: "Diggersby", NameCN: "掘地兔", Type1: "Normal", Type2: "Ground",},
	{NationalNo: 661, Name: "Fletchling", NameCN: "小箭雀", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 662, Name: "Fletchinder", NameCN: "火箭雀", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 663, Name: "Talonflame", NameCN: "烈箭鹰", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 664, Name: "Scatterbug", NameCN: "粉蝶虫", Type1: "Bug", },
	{NationalNo: 665, Name: "Spewpa", NameCN: "粉蝶蛹", Type1: "Bug", },
	{NationalNo: 666, Name: "Vivillon", NameCN: "彩粉蝶", Type1: "Bug", Type2: "Flying",},
	{NationalNo: 667, Name: "Litleo", NameCN: "小狮狮", Type1: "Fire", Type2: "Normal",},
	{NationalNo: 668, Name: "Pyroar", NameCN: "火炎狮", Type1: "Fire", Type2: "Normal",},
	{NationalNo: 669, Name: "Flabébé", NameCN: "花蓓蓓", Type1: "Fairy", },
	{NationalNo: 670, Name: "Floette", NameCN: "花叶蒂", Type1: "Fairy", },
	{NationalNo: 671, Name: "Florges", NameCN: "花洁夫人", Type1: "Fairy", },
	{NationalNo: 672, Name: "Skiddo", NameCN: "坐骑小羊", Type1: "Grass", },
	{NationalNo: 673, Name: "Gogoat", NameCN: "坐骑山羊", Type1: "Grass", },
	{NationalNo: 674, Name: "Pancham", NameCN: "顽皮熊猫", Type1: "Fighting", },
	{NationalNo: 675, Name: "Pangoro", NameCN: "流氓熊猫", Type1: "Fighting", Type2: "Dark",},
	{NationalNo: 676, Name: "Furfrou", NameCN: "多丽米亚", Type1: "Normal", },
	{NationalNo: 677, Name: "Espurr", NameCN: "妙喵", Type1: "Psychic", },
	{NationalNo: 678, Name: "Meowstic", NameCN: "超能妙喵", Type1: "Psychic", },
	{NationalNo: 679, Name: "Honedge", NameCN: "独剑鞘", Type1: "Steel", Type2: "Ghost",},
	{NationalNo: 680, Name: "Doublade", NameCN: "双剑鞘", Type1: "Steel", Type2: "Ghost",},
	{NationalNo: 681, Name: "Aegislash", NameCN: "坚盾剑怪", Type1: "Steel", Type2: "Ghost",},
	{NationalNo: 682, Name: "Spritzee", NameCN: "粉香香", Type1: "Fairy", },
	{NationalNo: 683, Name: "Aromatisse", NameCN: "芳香精", Type1: "Fairy", },
	{NationalNo: 684, Name: "Swirlix", NameCN: "绵绵泡芙", Type1: "Fairy", },
	{NationalNo: 685, Name: "Slurpuff", NameCN: "胖甜妮", Type1: "Fairy", },
	{NationalNo: 686, Name: "Inkay", NameCN: "好啦鱿", Type1: "Dark", Type2: "Psychic",},
	{NationalNo: 687, Name: "Malamar", NameCN: "乌贼王", Type1: "Dark", Type2: "Psychic",},
	{NationalNo: 688, Name: "Binacle", NameCN: "龟脚脚", Type1: "Rock", Type2: "Water",},
	{NationalNo: 689, Name: "Barbaracle", NameCN: "龟足巨铠", Type1: "Rock", Type2: "Water",},
	{NationalNo: 690, Name: "Skrelp", NameCN: "垃垃藻", Type1: "Poison", Type2: "Water",},
	{NationalNo: 691, Name: "Dragalge", NameCN: "毒藻龙", Type1: "Poison", Type2: "Dragon",},
	{NationalNo: 692, Name: "Clauncher", NameCN: "铁臂枪虾", Type1: "Water", },
	{NationalNo: 693, Name: "Clawitzer", NameCN: "钢炮臂虾", Type1: "Water", },
	{NationalNo: 694, Name: "Helioptile", NameCN: "伞电蜥", Type1: "Electric", Type2: "Normal",},
	{NationalNo: 695, Name: "Heliolisk", NameCN: "光电伞蜥", Type1: "Electric", Type2: "Normal",},
	{NationalNo: 696, Name: "Tyrunt", NameCN: "宝宝暴龙", Type1: "Rock", Type2: "Dragon",},
	{NationalNo: 697, Name: "Tyrantrum", NameCN: "怪颚龙", Type1: "Rock", Type2: "Dragon",},
	{NationalNo: 698, Name: "Amaura", NameCN: "冰雪龙", Type1: "Rock", Type2: "Ice",},
	{NationalNo: 699, Name: "Aurorus", NameCN: "冰雪巨龙", Type1: "Rock", Type2: "Ice",},
	{NationalNo: 700, Name: "Sylveon", NameCN: "仙子伊布", Type1: "Fairy", },
	{NationalNo: 701, Name: "Hawlucha", NameCN: "摔角鹰人", Type1: "Fighting", Type2: "Flying",},
	{NationalNo: 702, Name: "Dedenne", NameCN: "咚咚鼠", Type1: "Electric", Type2: "Fairy",},
	{NationalNo: 703, Name: "Carbink", NameCN: "小碎钻", Type1: "Rock", Type2: "Fairy",},
	{NationalNo: 704, Name: "Goomy", NameCN: "黏黏宝", Type1: "Dragon", },
	{NationalNo: 705, Name: "Sliggoo", NameCN: "黏美儿", Type1: "Dragon", },
	{NationalNo: 706, Name: "Goodra", NameCN: "黏美龙", Type1: "Dragon", },
	{NationalNo: 707, Name: "Klefki", NameCN: "钥圈儿", Type1: "Steel", Type2: "Fairy",},
	{NationalNo: 708, Name: "Phantump", NameCN: "小木灵", Type1: "Ghost", Type2: "Grass",},
	{NationalNo: 709, Name: "Trevenant", NameCN: "朽木妖", Type1: "Ghost", Type2: "Grass",},
	{NationalNo: 710, Name: "Pumpkaboo", NameCN: "南瓜精", Type1: "Ghost", Type2: "Grass",},
	{NationalNo: 711, Name: "Gourgeist", NameCN: "南瓜怪人", Type1: "Ghost", Type2: "Grass",},
	{NationalNo: 712, Name: "Bergmite", NameCN: "冰宝", Type1: "Ice", },
	{NationalNo: 713, Name: "Avalugg", NameCN: "冰岩怪", Type1: "Ice", },
	{NationalNo: 714, Name: "Noibat", NameCN: "嗡蝠", Type1: "Flying", Type2: "Dragon",},
	{NationalNo: 715, Name: "Noivern", NameCN: "音波龙", Type1: "Flying", Type2: "Dragon",},
	{NationalNo: 716, Name: "Xerneas", NameCN: "哲尔尼亚斯", Type1: "Fairy", },
	{NationalNo: 717, Name: "Yveltal", NameCN: "伊裴尔塔尔", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 718, Name: "Zygarde", NameCN: "基格尔德", Type1: "Dragon", Type2: "Ground",},
	{NationalNo: 719, Name: "Diancie", NameCN: "蒂安希", Type1: "Rock", Type2: "Fairy",},
	{NationalNo: 720, Name: "Hoopa", NameCN: "胡帕", Type1: "Psychic", Type2: "Ghost",},
	{NationalNo: 721, Name: "Volcanion", NameCN: "波尔凯尼恩", Type1: "Fire", Type2: "Water",},
	{NationalNo: 722, Name: "Rowlet", NameCN: "木木枭", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 723, Name: "Dartrix", NameCN: "投羽枭", Type1: "Grass", Type2: "Flying",},
	{NationalNo: 724, Name: "Decidueye", NameCN: "狙射树枭", Type1: "Grass", Type2: "Ghost",},
	{NationalNo: 725, Name: "Litten", NameCN: "火斑喵", Type1: "Fire", },
	{NationalNo: 726, Name: "Torracat", NameCN: "炎热喵", Type1: "Fire", },
	{NationalNo: 727, Name: "Incineroar", NameCN: "炽焰咆哮虎", Type1: "Fire", Type2: "Dark",},
	{NationalNo: 728, Name: "Popplio", NameCN: "球球海狮", Type1: "Water", },
	{NationalNo: 729, Name: "Brionne", NameCN: "花漾海狮", Type1: "Water", },
	{NationalNo: 730, Name: "Primarina", NameCN: "西狮海壬", Type1: "Water", Type2: "Fairy",},
	{NationalNo: 731, Name: "Pikipek", NameCN: "小笃儿", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 732, Name: "Trumbeak", NameCN: "喇叭啄鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 733, Name: "Toucannon", NameCN: "铳嘴大鸟", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 734, Name: "Yungoos", NameCN: "猫鼬少", Type1: "Normal", },
	{NationalNo: 735, Name: "Gumshoos", NameCN: "猫鼬探长", Type1: "Normal", },
	{NationalNo: 736, Name: "Grubbin", NameCN: "强颚鸡母虫", Type1: "Bug", },
	{NationalNo: 737, Name: "Charjabug", NameCN: "虫电宝", Type1: "Bug", Type2: "Electric",},
	{NationalNo: 738, Name: "Vikavolt", NameCN: "锹农炮虫", Type1: "Bug", Type2: "Electric",},
	{NationalNo: 739, Name: "Crabrawler", NameCN: "好胜蟹", Type1: "Fighting", },
	{NationalNo: 740, Name: "Crabominable", NameCN: "好胜毛蟹", Type1: "Fighting", Type2: "Ice",},
	{NationalNo: 741, Name: "Oricorio", NameCN: "花舞鸟", Type1: "Fire", Type2: "Flying",},
	{NationalNo: 742, Name: "Cutiefly", NameCN: "萌虻", Type1: "Bug", Type2: "Fairy",},
	{NationalNo: 743, Name: "Ribombee", NameCN: "蝶结萌虻", Type1: "Bug", Type2: "Fairy",},
	{NationalNo: 744, Name: "Rockruff", NameCN: "岩狗狗", Type1: "Rock", },
	{NationalNo: 745, Name: "Lycanroc", NameCN: "鬃岩狼人", Type1: "Rock", },
	{NationalNo: 746, Name: "Wishiwashi", NameCN: "弱丁鱼", Type1: "Water", },
	{NationalNo: 747, Name: "Mareanie", NameCN: "好坏星", Type1: "Poison", Type2: "Water",},
	{NationalNo: 748, Name: "Toxapex", NameCN: "超坏星", Type1: "Poison", Type2: "Water",},
	{NationalNo: 749, Name: "Mudbray", NameCN: "泥驴仔", Type1: "Ground", },
	{NationalNo: 750, Name: "Mudsdale", NameCN: "重泥挽马", Type1: "Ground", },
	{NationalNo: 751, Name: "Dewpider", NameCN: "滴蛛", Type1: "Water", Type2: "Bug",},
	{NationalNo: 752, Name: "Araquanid", NameCN: "滴蛛霸", Type1: "Water", Type2: "Bug",},
	{NationalNo: 753, Name: "Fomantis", NameCN: "伪螳草", Type1: "Grass", },
	{NationalNo: 754, Name: "Lurantis", NameCN: "兰螳花", Type1: "Grass", },
	{NationalNo: 755, Name: "Morelull", NameCN: "睡睡菇", Type1: "Grass", Type2: "Fairy",},
	{NationalNo: 756, Name: "Shiinotic", NameCN: "灯罩夜菇", Type1: "Grass", Type2: "Fairy",},
	{NationalNo: 757, Name: "Salandit", NameCN: "夜盗火蜥", Type1: "Poison", Type2: "Fire",},
	{NationalNo: 758, Name: "Salazzle", NameCN: "焰后蜥", Type1: "Poison", Type2: "Fire",},
	{NationalNo: 759, Name: "Stufful", NameCN: "童偶熊", Type1: "Normal", Type2: "Fighting",},
	{NationalNo: 760, Name: "Bewear", NameCN: "穿着熊", Type1: "Normal", Type2: "Fighting",},
	{NationalNo: 761, Name: "Bounsweet", NameCN: "甜竹竹", Type1: "Grass", },
	{NationalNo: 762, Name: "Steenee", NameCN: "甜舞妮", Type1: "Grass", },
	{NationalNo: 763, Name: "Tsareena", NameCN: "甜冷美后", Type1: "Grass", },
	{NationalNo: 764, Name: "Comfey", NameCN: "花疗环环", Type1: "Fairy", },
	{NationalNo: 765, Name: "Oranguru", NameCN: "智挥猩", Type1: "Normal", Type2: "Psychic",},
	{NationalNo: 766, Name: "Passimian", NameCN: "投掷猴", Type1: "Fighting", },
	{NationalNo: 767, Name: "Wimpod", NameCN: "胆小虫", Type1: "Bug", Type2: "Water",},
	{NationalNo: 768, Name: "Golisopod", NameCN: "具甲武者", Type1: "Bug", Type2: "Water",},
	{NationalNo: 769, Name: "Sandygast", NameCN: "沙丘娃", Type1: "Ghost", Type2: "Ground",},
	{NationalNo: 770, Name: "Palossand", NameCN: "噬沙堡爷", Type1: "Ghost", Type2: "Ground",},
	{NationalNo: 771, Name: "Pyukumuku", NameCN: "拳海参", Type1: "Water", },
	{NationalNo: 772, Name: "Type: Null", NameCN: "属性：空", Type1: "Normal", },
	{NationalNo: 773, Name: "Silvally", NameCN: "银伴战兽", Type1: "Normal", },
	{NationalNo: 774, Name: "Minior", NameCN: "小陨星", Type1: "Rock", Type2: "Flying",},
	{NationalNo: 775, Name: "Komala", NameCN: "树枕尾熊", Type1: "Normal", },
	{NationalNo: 776, Name: "Turtonator", NameCN: "爆焰龟兽", Type1: "Fire", Type2: "Dragon",},
	{NationalNo: 777, Name: "Togedemaru", NameCN: "托戈德玛尔", Type1: "Electric", Type2: "Steel",},
	{NationalNo: 778, Name: "Mimikyu", NameCN: "谜拟Ｑ", Type1: "Ghost", Type2: "Fairy",},
	{NationalNo: 779, Name: "Bruxish", NameCN: "磨牙彩皮鱼", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 780, Name: "Drampa", NameCN: "老翁龙", Type1: "Normal", Type2: "Dragon",},
	{NationalNo: 781, Name: "Dhelmise", NameCN: "破破舵轮", Type1: "Ghost", Type2: "Grass",},
	{NationalNo: 782, Name: "Jangmo-o", NameCN: "心鳞宝", Type1: "Dragon", },
	{NationalNo: 783, Name: "Hakamo-o", NameCN: "鳞甲龙", Type1: "Dragon", Type2: "Fighting",},
	{NationalNo: 784, Name: "Kommo-o", NameCN: "杖尾鳞甲龙", Type1: "Dragon", Type2: "Fighting",},
	{NationalNo: 785, Name: "Tapu Koko", NameCN: "卡璞・鸣鸣", Type1: "Electric", Type2: "Fairy",},
	{NationalNo: 786, Name: "Tapu Lele", NameCN: "卡璞・蝶蝶", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 787, Name: "Tapu Bulu", NameCN: "卡璞・哞哞", Type1: "Grass", Type2: "Fairy",},
	{NationalNo: 788, Name: "Tapu Fini", NameCN: "卡璞・鳍鳍", Type1: "Water", Type2: "Fairy",},
	{NationalNo: 789, Name: "Cosmog", NameCN: "科斯莫古", Type1: "Psychic", },
	{NationalNo: 790, Name: "Cosmoem", NameCN: "科斯莫姆", Type1: "Psychic", },
	{NationalNo: 791, Name: "Solgaleo", NameCN: "索尔迦雷欧", Type1: "Psychic", Type2: "Steel",},
	{NationalNo: 792, Name: "Lunala", NameCN: "露奈雅拉", Type1: "Psychic", Type2: "Ghost",},
	{NationalNo: 793, Name: "Nihilego", NameCN: "虚吾伊德", Type1: "Rock", Type2: "Poison",},
	{NationalNo: 794, Name: "Buzzwole", NameCN: "爆肌蚊", Type1: "Bug", Type2: "Fighting",},
	{NationalNo: 795, Name: "Pheromosa", NameCN: "费洛美螂", Type1: "Bug", Type2: "Fighting",},
	{NationalNo: 796, Name: "Xurkitree", NameCN: "电束木", Type1: "Electric", },
	{NationalNo: 797, Name: "Celesteela", NameCN: "铁火辉夜", Type1: "Steel", Type2: "Flying",},
	{NationalNo: 798, Name: "Kartana", NameCN: "纸御剑", Type1: "Grass", Type2: "Steel",},
	{NationalNo: 799, Name: "Guzzlord", NameCN: "恶食大王", Type1: "Dark", Type2: "Dragon",},
	{NationalNo: 800, Name: "Necrozma", NameCN: "奈克洛兹玛", Type1: "Psychic", },
	{NationalNo: 801, Name: "Magearna", NameCN: "玛机雅娜", Type1: "Steel", Type2: "Fairy",},
	{NationalNo: 802, Name: "Marshadow", NameCN: "玛夏多", Type1: "Fighting", Type2: "Ghost",},
	{NationalNo: 803, Name: "Poipole", NameCN: "毒贝比", Type1: "Poison", },
	{NationalNo: 804, Name: "Naganadel", NameCN: "四颚针龙", Type1: "Poison", Type2: "Dragon",},
	{NationalNo: 805, Name: "Stakataka", NameCN: "垒磊石", Type1: "Rock", Type2: "Steel",},
	{NationalNo: 806, Name: "Blacephalon", NameCN: "砰头小丑", Type1: "Fire", Type2: "Ghost",},
	{NationalNo: 807, Name: "Zeraora", NameCN: "捷拉奥拉", Type1: "Electric", },
	{NationalNo: 808, Name: "Meltan", NameCN: "美录坦", Type1: "Steel", },
	{NationalNo: 809, Name: "Melmetal", NameCN: "美录梅塔", Type1: "Steel", },
	{NationalNo: 810, Name: "Grookey", NameCN: "敲音猴", Type1: "Grass", },
	{NationalNo: 811, Name: "Thwackey", NameCN: "啪咚猴", Type1: "Grass", },
	{NationalNo: 812, Name: "Rillaboom", NameCN: "轰擂金刚猩", Type1: "Grass", },
	{NationalNo: 813, Name: "Scorbunny", NameCN: "炎兔儿", Type1: "Fire", },
	{NationalNo: 814, Name: "Raboot", NameCN: "腾蹴小将", Type1: "Fire", },
	{NationalNo: 815, Name: "Cinderace", NameCN: "闪焰王牌", Type1: "Fire", },
	{NationalNo: 816, Name: "Sobble", NameCN: "泪眼蜥", Type1: "Water", },
	{NationalNo: 817, Name: "Drizzile", NameCN: "变涩蜥", Type1: "Water", },
	{NationalNo: 818, Name: "Inteleon", NameCN: "千面避役", Type1: "Water", },
	{NationalNo: 819, Name: "Skwovet", NameCN: "贪心栗鼠", Type1: "Normal", },
	{NationalNo: 820, Name: "Greedent", NameCN: "藏饱栗鼠", Type1: "Normal", },
	{NationalNo: 821, Name: "Rookidee", NameCN: "稚山雀", Type1: "Flying", },
	{NationalNo: 822, Name: "Corvisquire", NameCN: "蓝鸦", Type1: "Flying", },
	{NationalNo: 823, Name: "Corviknight", NameCN: "钢铠鸦", Type1: "Flying", Type2: "Steel",},
	{NationalNo: 824, Name: "Blipbug", NameCN: "索侦虫", Type1: "Bug", },
	{NationalNo: 825, Name: "Dottler", NameCN: "天罩虫", Type1: "Bug", Type2: "Psychic",},
	{NationalNo: 826, Name: "Orbeetle", NameCN: "以欧路普", Type1: "Bug", Type2: "Psychic",},
	{NationalNo: 827, Name: "Nickit", NameCN: "偷儿狐", Type1: "Dark", },
	{NationalNo: 828, Name: "Thievul", NameCN: "狐大盗", Type1: "Dark", },
	{NationalNo: 829, Name: "Gossifleur", NameCN: "幼棉棉", Type1: "Grass", },
	{NationalNo: 830, Name: "Eldegoss", NameCN: "白蓬蓬", Type1: "Grass", },
	{NationalNo: 831, Name: "Wooloo", NameCN: "毛辫羊", Type1: "Normal", },
	{NationalNo: 832, Name: "Dubwool", NameCN: "毛毛角羊", Type1: "Normal", },
	{NationalNo: 833, Name: "Chewtle", NameCN: "咬咬龟", Type1: "Water", },
	{NationalNo: 834, Name: "Drednaw", NameCN: "暴噬龟", Type1: "Water", Type2: "Rock",},
	{NationalNo: 835, Name: "Yamper", NameCN: "来电汪", Type1: "Electric", },
	{NationalNo: 836, Name: "Boltund", NameCN: "逐电犬", Type1: "Electric", },
	{NationalNo: 837, Name: "Rolycoly", NameCN: "小炭仔", Type1: "Rock", },
	{NationalNo: 838, Name: "Carkol", NameCN: "大炭车", Type1: "Rock", Type2: "Fire",},
	{NationalNo: 839, Name: "Coalossal", NameCN: "巨炭山", Type1: "Rock", Type2: "Fire",},
	{NationalNo: 840, Name: "Applin", NameCN: "啃果虫", Type1: "Grass", Type2: "Dragon",},
	{NationalNo: 841, Name: "Flapple", NameCN: "苹裹龙", Type1: "Grass", Type2: "Dragon",},
	{NationalNo: 842, Name: "Appletun", NameCN: "丰蜜龙", Type1: "Grass", Type2: "Dragon",},
	{NationalNo: 843, Name: "Silicobra", NameCN: "沙包蛇", Type1: "Ground", },
	{NationalNo: 844, Name: "Sandaconda", NameCN: "沙螺蟒", Type1: "Ground", },
	{NationalNo: 845, Name: "Cramorant", NameCN: "古月鸟", Type1: "Flying", Type2: "Water",},
	{NationalNo: 846, Name: "Arrokuda", NameCN: "刺梭鱼", Type1: "Water", },
	{NationalNo: 847, Name: "Barraskewda", NameCN: "戽斗尖梭", Type1: "Water", },
	{NationalNo: 848, Name: "Toxel", NameCN: "毒电婴", Type1: "Electric", Type2: "Poison",},
	{NationalNo: 849, Name: "Toxtricity", NameCN: "毒电兔", Type1: "Electric", Type2: "Poison",},
	{NationalNo: 850, Name: "Sizzlipede", NameCN: "烧火蚣", Type1: "Fire", Type2: "Bug",},
	{NationalNo: 851, Name: "Centiskorch", NameCN: "焚焰蚣", Type1: "Fire", Type2: "Bug",},
	{NationalNo: 852, Name: "Clobbopus", NameCN: "拳拳蛸", Type1: "Fighting", },
	{NationalNo: 853, Name: "Grapploct", NameCN: "八爪武师", Type1: "Fighting", },
	{NationalNo: 854, Name: "Sinistea", NameCN: "来悲茶", Type1: "Ghost", },
	{NationalNo: 855, Name: "Polteageist", NameCN: "怖思壶", Type1: "Ghost", },
	{NationalNo: 856, Name: "Hatenna", NameCN: "迷布莉姆", Type1: "Psychic", },
	{NationalNo: 857, Name: "Hattrem", NameCN: "提布莉姆", Type1: "Psychic", },
	{NationalNo: 858, Name: "Hatterene", NameCN: "布莉姆温", Type1: "Psychic", Type2: "Fairy",},
	{NationalNo: 859, Name: "Impidimp", NameCN: "捣蛋小妖", Type1: "Dark", Type2: "Fairy",},
	{NationalNo: 860, Name: "Morgrem", NameCN: "诈唬魔", Type1: "Dark", Type2: "Fairy",},
	{NationalNo: 861, Name: "Grimmsnarl", NameCN: "长毛巨魔", Type1: "Dark", Type2: "Fairy",},
	{NationalNo: 862, Name: "Obstagoon", NameCN: "堵拦熊", Type1: "Dark", Type2: "Normal",},
	{NationalNo: 863, Name: "Perrserker", NameCN: "喵头目", Type1: "Steel", },
	{NationalNo: 864, Name: "Cursola", NameCN: "魔灵珊瑚", Type1: "Ghost", },
	{NationalNo: 865, Name: "Sirfetch'd", NameCN: "葱游兵", Type1: "Fighting", },
	{NationalNo: 866, Name: "Mr. Rime", NameCN: "踏冰人偶", Type1: "Ice", Type2: "Psychic",},
	{NationalNo: 867, Name: "Runerigus", NameCN: "死神板", Type1: "Ground", Type2: "Ghost",},
	{NationalNo: 868, Name: "Milcery", NameCN: "小仙奶", Type1: "Fairy", },
	{NationalNo: 869, Name: "Alcremie", NameCN: "霜奶仙", Type1: "Fairy", },
	{NationalNo: 870, Name: "Falinks", NameCN: "列阵兵", Type1: "Fighting", },
	{NationalNo: 871, Name: "Pincurchin", NameCN: "啪嚓海胆", Type1: "Electric", },
	{NationalNo: 872, Name: "Snom", NameCN: "雪吞虫", Type1: "Ice", Type2: "Bug",},
	{NationalNo: 873, Name: "Frosmoth", NameCN: "雪绒蛾", Type1: "Ice", Type2: "Bug",},
	{NationalNo: 874, Name: "Stonjourner", NameCN: "巨石丁", Type1: "Rock", },
	{NationalNo: 875, Name: "Eiscue", NameCN: "冰砌鹅", Type1: "Ice", },
	{NationalNo: 876, Name: "Indeedee", NameCN: "爱管侍", Type1: "Psychic", Type2: "Normal",},
	{NationalNo: 877, Name: "Morpeko", NameCN: "莫鲁贝可", Type1: "Electric", Type2: "Dark",},
	{NationalNo: 878, Name: "Cufant", NameCN: "铜象", Type1: "Steel", },
	{NationalNo: 879, Name: "Copperajah", NameCN: "大王铜象", Type1: "Steel", },
	{NationalNo: 880, Name: "Dracozolt", NameCN: "雷鸟龙", Type1: "Electric", Type2: "Dragon",},
	{NationalNo: 881, Name: "Arctozolt", NameCN: "雷鸟海兽", Type1: "Electric", Type2: "Ice",},
	{NationalNo: 882, Name: "Dracovish", NameCN: "鳃鱼龙", Type1: "Water", Type2: "Dragon",},
	{NationalNo: 883, Name: "Arctovish", NameCN: "鳃鱼海兽", Type1: "Water", Type2: "Ice",},
	{NationalNo: 884, Name: "Duraludon", NameCN: "铝钢龙", Type1: "Steel", Type2: "Dragon",},
	{NationalNo: 885, Name: "Dreepy", NameCN: "多龙梅西亚", Type1: "Dragon", Type2: "Ghost",},
	{NationalNo: 886, Name: "Drakloak", NameCN: "多龙奇", Type1: "Dragon", Type2: "Ghost",},
	{NationalNo: 887, Name: "Dragapult", NameCN: "多龙巴鲁托", Type1: "Dragon", Type2: "Ghost",},
	{NationalNo: 888, Name: "Zacian", NameCN: "苍响", Type1: "Fairy", },
	{NationalNo: 889, Name: "Zamazenta", NameCN: "藏玛然特", Type1: "Fighting", },
	{NationalNo: 890, Name: "Eternatus", NameCN: "无极汰那", Type1: "Poison", Type2: "Dragon",},
	{NationalNo: 891, Name: "Kubfu", NameCN: "熊徒弟", Type1: "Fighting", },
	{NationalNo: 892, Name: "Urshifu", NameCN: "武道熊师", Type1: "Fighting", Type2: "Dark",},
	{NationalNo: 893, Name: "Zarude", NameCN: "萨戮德", Type1: "Dark", Type2: "Grass",},
	{NationalNo: 894, Name: "Regieleki", NameCN: "雷吉艾勒奇", Type1: "Electric", },
	{NationalNo: 895, Name: "Regidrago", NameCN: "雷吉铎拉戈", Type1: "Dragon", },
	{NationalNo: 896, Name: "Glastrier", NameCN: "雪暴马", Type1: "Ice", },
	{NationalNo: 897, Name: "Spectrier", NameCN: "幽灵马", Type1: "Ghost", },
	{NationalNo: 898, Name: "Calyrex", NameCN: "蕾冠王", Type1: "Psychic", Type2: "Grass",},
	{NationalNo: 899, Name: "Wyrdeer", NameCN: "诡角鹿", Type1: "Normal", Type2: "Psychic",},
	{NationalNo: 900, Name: "Kleavor", NameCN: "劈斧螳螂", Type1: "Bug", Type2: "Rock",},
	{NationalNo: 901, Name: "Ursaluna", NameCN: "月月熊", Type1: "Ground", Type2: "Normal",},
	{NationalNo: 902, Name: "Basculegion", NameCN: "幽尾玄鱼", Type1: "Water", Type2: "Ghost",},
	{NationalNo: 903, Name: "Sneasler", NameCN: "大狃拉", Type1: "Fighting", Type2: "Poison",},
	{NationalNo: 904, Name: "Overqwil", NameCN: "万针鱼", Type1: "Dark", Type2: "Poison",},
	{NationalNo: 905, Name: "Enamorus", NameCN: "眷恋云", Type1: "Fairy", Type2: "Flying",},
	{NationalNo: 906, Name: "Sprigatito", NameCN: "新叶喵", Type1: "Grass", },
	{NationalNo: 907, Name: "Floragato", NameCN: "蒂蕾喵", Type1: "Grass", },
	{NationalNo: 908, Name: "Meowscarada", NameCN: "魔幻假面喵", Type1: "Grass", Type2: "Dark",},
	{NationalNo: 909, Name: "Fuecoco", NameCN: "呆火鳄", Type1: "Fire", },
	{NationalNo: 910, Name: "Crocalor", NameCN: "炙烫鳄", Type1: "Fire", },
	{NationalNo: 911, Name: "Skeledirge", NameCN: "骨纹巨声鳄", Type1: "Fire", Type2: "Ghost",},
	{NationalNo: 912, Name: "Quaxly", NameCN: "润水鸭", Type1: "Water", },
	{NationalNo: 913, Name: "Quaxwell", NameCN: "涌跃鸭", Type1: "Water", },
	{NationalNo: 914, Name: "Quaquaval", NameCN: "狂欢浪舞鸭", Type1: "Water", Type2: "Fighting",},
	{NationalNo: 915, Name: "Lechonk", NameCN: "爱吃豚", Type1: "Normal", },
	{NationalNo: 916, Name: "Oinkologne", NameCN: "飘香豚", Type1: "Normal", },
	{NationalNo: 917, Name: "Tarountula", NameCN: "团珠蛛", Type1: "Bug", },
	{NationalNo: 918, Name: "Spidops", NameCN: "操陷蛛", Type1: "Bug", },
	{NationalNo: 919, Name: "Nymble", NameCN: "豆蟋蟀", Type1: "Bug", },
	{NationalNo: 920, Name: "Lokix", NameCN: "烈腿蝗", Type1: "Bug", Type2: "Dark",},
	{NationalNo: 921, Name: "Pawmi", NameCN: "布拨", Type1: "Electric", },
	{NationalNo: 922, Name: "Pawmo", NameCN: "布土拨", Type1: "Electric", Type2: "Fighting",},
	{NationalNo: 923, Name: "Pawmot", NameCN: "巴布土拨", Type1: "Electric", Type2: "Fighting",},
	{NationalNo: 924, Name: "Tandemaus", NameCN: "一对鼠", Type1: "Normal", },
	{NationalNo: 925, Name: "Maushold", NameCN: "一家鼠", Type1: "Normal", },
	{NationalNo: 926, Name: "Fidough", NameCN: "狗仔包", Type1: "Fairy", },
	{NationalNo: 927, Name: "Dachsbun", NameCN: "麻花犬", Type1: "Fairy", },
	{NationalNo: 928, Name: "Smoliv", NameCN: "迷你芙", Type1: "Grass", Type2: "Normal",},
	{NationalNo: 929, Name: "Dolliv", NameCN: "奥利纽", Type1: "Grass", Type2: "Normal",},
	{NationalNo: 930, Name: "Arboliva", NameCN: "奥利瓦", Type1: "Grass", Type2: "Normal",},
	{NationalNo: 931, Name: "Squawkabilly", NameCN: "怒鹦哥", Type1: "Normal", Type2: "Flying",},
	{NationalNo: 932, Name: "Nacli", NameCN: "盐石宝", Type1: "Rock", },
	{NationalNo: 933, Name: "Naclstack", NameCN: "盐石垒", Type1: "Rock", },
	{NationalNo: 934, Name: "Garganacl", NameCN: "盐石巨灵", Type1: "Rock", },
	{NationalNo: 935, Name: "Charcadet", NameCN: "炭小侍", Type1: "Fire", },
	{NationalNo: 936, Name: "Armarouge", NameCN: "红莲铠骑", Type1: "Fire", Type2: "Psychic",},
	{NationalNo: 937, Name: "Ceruledge", NameCN: "苍炎刃鬼", Type1: "Fire", Type2: "Ghost",},
	{NationalNo: 938, Name: "Tadbulb", NameCN: "光蚪仔", Type1: "Electric", },
	{NationalNo: 939, Name: "Bellibolt", NameCN: "电肚蛙", Type1: "Electric", },
	{NationalNo: 940, Name: "Wattrel", NameCN: "电海燕", Type1: "Electric", Type2: "Flying",},
	{NationalNo: 941, Name: "Kilowattrel", NameCN: "大电海燕", Type1: "Electric", Type2: "Flying",},
	{NationalNo: 942, Name: "Maschiff", NameCN: "獒教父", Type1: "Dark", },
	{NationalNo: 943, Name: "Mabosstiff", NameCN: "獒教父", Type1: "Dark", },
	{NationalNo: 944, Name: "Shroodle", NameCN: "滋汁鼹", Type1: "Poison", Type2: "Normal",},
	{NationalNo: 945, Name: "Grafaiai", NameCN: "涂标客", Type1: "Poison", Type2: "Normal",},
	{NationalNo: 946, Name: "Bramblin", NameCN: "纳噬草", Type1: "Grass", Type2: "Ghost",},
	{NationalNo: 947, Name: "Brambleghast", NameCN: "怖纳噬草", Type1: "Grass", Type2: "Ghost",},
	{NationalNo: 948, Name: "Toedscool", NameCN: "原野水母", Type1: "Ground", Type2: "Grass",},
	{NationalNo: 949, Name: "Toedscruel", NameCN: "陆地水母", Type1: "Ground", Type2: "Grass",},
	{NationalNo: 950, Name: "Klawf", NameCN: "毛崖蟹", Type1: "Rock", },
	{NationalNo: 951, Name: "Capsakid", NameCN: "热辣娃", Type1: "Grass", },
	{NationalNo: 952, Name: "Scovillain", NameCN: "狠辣椒", Type1: "Grass", Type2: "Fire",},
	{NationalNo: 953, Name: "Rellor", NameCN: "虫滚泥", Type1: "Bug", },
	{NationalNo: 954, Name: "Rabsca", NameCN: "虫甲圣", Type1: "Bug", Type2: "Psychic",},
	{NationalNo: 955, Name: "Flittle", NameCN: "飘飘雏", Type1: "Psychic", },
	{NationalNo: 956, Name: "Espathra", NameCN: "超能艳鸵", Type1: "Psychic", },
	{NationalNo: 957, Name: "Tinkatink", NameCN: "小锻匠", Type1: "Fairy", Type2: "Steel",},
	{NationalNo: 958, Name: "Tinkatuff", NameCN: "巧锻匠", Type1: "Fairy", Type2: "Steel",},
	{NationalNo: 959, Name: "Tinkaton", NameCN: "巨锻匠", Type1: "Fairy", Type2: "Steel",},
	{NationalNo: 960, Name: "Wiglett", NameCN: "海地鼠", Type1: "Water", },
	{NationalNo: 961, Name: "Wugtrio", NameCN: "三海地鼠", Type1: "Water", },
	{NationalNo: 962, Name: "Bombirdier", NameCN: "下石鸟", Type1: "Flying", Type2: "Dark",},
	{NationalNo: 963, Name: "Finizen", NameCN: "波普海豚", Type1: "Water", },
	{NationalNo: 964, Name: "Palafin", NameCN: "海豚侠", Type1: "Water", },
	{NationalNo: 965, Name: "Varoom", NameCN: "噗隆隆", Type1: "Steel", Type2: "Poison",},
	{NationalNo: 966, Name: "Revavroom", NameCN: "普隆隆姆", Type1: "Steel", Type2: "Poison",},
	{NationalNo: 967, Name: "Cyclizar", NameCN: "摩托蜥", Type1: "Dragon", Type2: "Normal",},
	{NationalNo: 968, Name: "Orthworm", NameCN: "拖拖蚓", Type1: "Steel", },
	{NationalNo: 969, Name: "Glimmet", NameCN: "晶光芽", Type1: "Rock", Type2: "Poison",},
	{NationalNo: 970, Name: "Glimmora", NameCN: "晶光花", Type1: "Rock", Type2: "Poison",},
	{NationalNo: 971, Name: "Greavard", NameCN: "墓仔狗", Type1: "Ghost", },
	{NationalNo: 972, Name: "Houndstone", NameCN: "墓扬犬", Type1: "Ghost", },
	{NationalNo: 973, Name: "Flamigo", NameCN: "缠红鹤", Type1: "Flying", Type2: "Fighting",},
	{NationalNo: 974, Name: "Cetoddle", NameCN: "走鲸", Type1: "Ice", },
	{NationalNo: 975, Name: "Cetitan", NameCN: "浩大鲸", Type1: "Ice", },
	{NationalNo: 976, Name: "Veluza", NameCN: "轻身鳕", Type1: "Water", Type2: "Psychic",},
	{NationalNo: 977, Name: "Dondozo", NameCN: "吃吼霸", Type1: "Water", },
	{NationalNo: 978, Name: "Tatsugiri", NameCN: "米立龙", Type1: "Dragon", Type2: "Water",},
	{NationalNo: 979, Name: "Annihilape", NameCN: "弃世猴", Type1: "Fighting", Type2: "Ghost",},
	{NationalNo: 980, Name: "Clodsire", NameCN: "土王", Type1: "Poison", Type2: "Ground",},
	{NationalNo: 981, Name: "Farigiraf", NameCN: "奇麒麟", Type1: "Normal", Type2: "Psychic",},
	{NationalNo: 982, Name: "Dudunsparce", NameCN: "土龙节节", Type1: "Normal", },
	{NationalNo: 983, Name: "Kingambit", NameCN: "仆刀将军", Type1: "Dark", Type2: "Steel",},
	{NationalNo: 984, Name: "Great Tusk", NameCN: "雄伟牙", Type1: "Ground", Type2: "Fighting",},
	{NationalNo: 985, Name: "Scream Tail", NameCN: "吼叫尾", Type1: "Fairy", Type2: "Psychic",},
	{NationalNo: 986, Name: "Brute Bonnet", NameCN: "猛恶菇", Type1: "Grass", Type2: "Dark",},
	{NationalNo: 987, Name: "Flutter Mane", NameCN: "振翼发", Type1: "Ghost", Type2: "Fairy",},
	{NationalNo: 988, Name: "Slither Wing", NameCN: "爬地翅", Type1: "Bug", Type2: "Fighting",},
	{NationalNo: 989, Name: "Sandy Shocks", NameCN: "沙铁皮", Type1: "Electric", Type2: "Ground",},
	{NationalNo: 990, Name: "Iron Treads", NameCN: "铁辙迹", Type1: "Ground", Type2: "Steel",},
	{NationalNo: 991, Name: "Iron Bundle", NameCN: "铁包袱", Type1: "Ice", Type2: "Water",},
	{NationalNo: 992, Name: "Iron Hands", NameCN: "铁臂膀", Type1: "Fighting", Type2: "Electric",},
	{NationalNo: 993, Name: "Iron Jugulis", NameCN: "铁脖颈", Type1: "Dark", Type2: "Flying",},
	{NationalNo: 994, Name: "Iron Moth", NameCN: "铁毒蛾", Type1: "Fire", Type2: "Poison",},
	{NationalNo: 995, Name: "Iron Thorns", NameCN: "铁荆棘", Type1: "Rock", Type2: "Electric",},
	{NationalNo: 996, Name: "Frigibax", NameCN: "凉脊龙", Type1: "Dragon", Type2: "Ice",},
	{NationalNo: 997, Name: "Arctibax", NameCN: "冻脊龙", Type1: "Dragon", Type2: "Ice",},
	{NationalNo: 998, Name: "Baxcalibur", NameCN: "戟脊龙", Type1: "Dragon", Type2: "Ice",},
	{NationalNo: 999, Name: "Gimmighoul", NameCN: "索财灵", Type1: "Ghost", },
	{NationalNo: 1000, Name: "Gholdengo", NameCN: "赛富豪", Type1: "Steel", Type2: "Ghost",},
	{NationalNo: 1001, Name: "Wo-Chien", NameCN: "古简蜗", Type1: "Dark", Type2: "Grass",},
	{NationalNo: 1002, Name: "Chien-Pao", NameCN: "古剑豹", Type1: "Dark", Type2: "Ice",},
	{NationalNo: 1003, Name: "Ting-Lu", NameCN: "古鼎鹿", Type1: "Dark", Type2: "Ground",},
	{NationalNo: 1004, Name: "Chi-Yu", NameCN: "古玉鱼", Type1: "Dark", Type2: "Fire",},
	{NationalNo: 1005, Name: "Roaring Moon", NameCN: "轰鸣月", Type1: "Dragon", Type2: "Dark",},
	{NationalNo: 1006, Name: "Iron Valiant", NameCN: "铁武者", Type1: "Fairy", Type2: "Fighting",},
	{NationalNo: 1007, Name: "Koraidon", NameCN: "故勒顿", Type1: "Fighting", Type2: "Dragon",},
	{NationalNo: 1008, Name: "Miraidon", NameCN: "密勒顿", Type1: "Electric", Type2: "Dragon",},
	{NationalNo: 1009, Name: "Walking Wake", NameCN: "波荡水", Type1: "Water", Type2: "Dragon",},
	{NationalNo: 1010, Name: "Iron Leaves", NameCN: "铁斑叶", Type1: "Grass", Type2: "Psychic",},
	{NationalNo: 1011, Name: "Dipplin", NameCN: "裹蜜虫", Type1: "Grass", Type2: "Dragon",},
	{NationalNo: 1012, Name: "Poltchageist", NameCN: "斯魔茶", Type1: "Grass", Type2: "Ghost",},
	{NationalNo: 1013, Name: "Sinistcha", NameCN: "来悲粗茶", Type1: "Grass", Type2: "Ghost",},
	{NationalNo: 1014, Name: "Okidogi", NameCN: "够赞狗", Type1: "Poison", Type2: "Fighting",},
	{NationalNo: 1015, Name: "Munkidori", NameCN: "愿增猿", Type1: "Poison", Type2: "Psychic",},
	{NationalNo: 1016, Name: "Fezandipiti", NameCN: "吉雉鸡", Type1: "Poison", Type2: "Fairy",},
	{NationalNo: 1017, Name: "Ogerpon", NameCN: "厄诡椪", Type1: "Grass", },
	{NationalNo: 1018, Name: "Archaludon", NameCN: "铝钢桥龙", Type1: "Steel", Type2: "Dragon",},
	{NationalNo: 1019, Name: "Hydrapple", NameCN: "蜜集大蛇", Type1: "Grass", Type2: "Dragon",},
	{NationalNo: 1020, Name: "Gouging Fire", NameCN: "破空火", Type1: "Fire", Type2: "Dragon",},
	{NationalNo: 1021, Name: "Raging Bolt", NameCN: "猛雷鼓", Type1: "Electric", Type2: "Dragon",},
	{NationalNo: 1022, Name: "Iron Boulder", NameCN: "铁磐岩", Type1: "Rock", Type2: "Psychic",},
	{NationalNo: 1023, Name: "Iron Crown", NameCN: "铁头壳", Type1: "Steel", Type2: "Psychic",},
	{NationalNo: 1024, Name: "Terapagos", NameCN: "太乐巴戈斯", Type1: "Normal", },
	{NationalNo: 1025, Name: "Pecharunt", NameCN: "桃歹郎", Type1: "Poison", Type2: "Ghost",},
}
